### DISCUSSION TITLE
DNS server setup

### DISCUSSION THREAD

**Discussion by patrick-begou** [bluebanquise/bluebanquise#1106] [Cluster deployment]
I all,

I'm stuck with a DNS problem in BlueBanquise with name resolution. My bluebanquise network is ```localcluster.priv```
```
bb_domain_name: localcluster.priv
bb_time_zone: Europe/Paris
```

Named is running on the management node, and I have a forwarder in the inventory:
```
dns_server_forwarders:
- 194.254.66.12
dns_server_recursion: yes
```
I can resolve all the FDQN excepted those in a local private network ```hmg.priv```. This network is known by the forwarder. 

### On the management node running bluebanquise named setup:

**dig @194.254.66.12 proxmost1.hmg.priv**
```
;; QUESTION SECTION:
;proxmost1.hmg.priv.		IN	A

;; ANSWER SECTION:
proxmost1.hmg.priv.	86400	IN	A	192.168.22.225

;; AUTHORITY SECTION:
hmg.priv.		86400	IN	NS	ns-1.grenet.fr.
hmg.priv.		86400	IN	NS	dns.hmg.inpg.fr.

;; Query time: 2 msec
;; SERVER: 194.254.66.12#53(194.254.66.12)
```

but:
**dig @localhost proxmost1.hmg.priv**
```
;; QUESTION SECTION:
;proxmost1.hmg.priv.		IN	A

;; AUTHORITY SECTION:
.			8241	IN	SOA	a.root-servers.net. nstld.verisign-grs.com. 2025050700 1800 900 604800 86400

;; Query time: 2 msec
;; SERVER: ::1#53(::1)
```

And I get **NXDOMAIN** answer.

A way to solve this ?

Thanks

**Comment by oxedions** [comment]
Hey @patrick-begou  !

Can you give me the content of your /etc/resolv.conf and also the result of this command (please adapt to your external interface name):

```
(ansible_venv) bluebanquise@mgt1:~$ nmcli con show enp1s0 | grep ipv4.dns-search
ipv4.dns-search:                        cluster.local.
(ansible_venv) bluebanquise@mgt1:~$ 
```

**Reply by patrick-begou** [reply]
Hi Benoît,

On the management node:

```
(ansible_venv) [bluebanquise@osorno-fe ~]$ nmcli con show ens18 | grep ipv4.dns-search
ipv4.dns-search:                        legi.grenoble-inp.fr
```
and
```
(ansible_venv) [bluebanquise@osorno-fe ~]$ cat /etc/resolv.conf
# Generated by NetworkManager
search legi.grenoble-inp.fr localcluster.priv
nameserver 194.254.66.12
nameserver 172.30.1.64
```

172.30.1.64 is the private IP of the management node.

**Reply by oxedions** [reply]
Thanks !

Can you try something: manually edit /etc/resolv.conf (I know we shouldnt do that, but try this, its safe as anyway NetworkManager will overwrite it later), and replace:

`search legi.grenoble-inp.fr localcluster.priv
`
by

`search legi.grenoble-inp.fr localcluster.priv hmg.priv
`
And try immediatly after that the checks commands (dig, ping, etc).
Does it solves your issue ?

Also, from your system, quering your localhost dns, are you able to dig external domains, like google.com etc ?

**Reply by patrick-begou** [reply]
Hi Benoît,

No it does not help. It looks like if requests on FDQN ending in ```.priv``` and not managed by bluebanquise nameserver (outside ```localcluster.priv```) are not transmitted properly to my forwarder but to DNS root servers. And of course these root servers do not know anything about our internal network.
I can resolve everything (including  ```google.com``` excepted```'xxxx.priv``` when ```xxxx``` is not ```localcluster```
I've checked in the named setup generated by bluebanquise roles but no idea about this behavior.
May be should I change my ```bb_domain_name``` to ```localcluster.calcul```` as a workaround but this may have a large impact now no ?

**Reply by patrick-begou** [reply]
Just to fix my observations, from the login node

**1) explicitly requesting the forwarder:**
```
bash-5.1$ dig @194.254.66.12 proxmost1.hmg.priv  A +nsid
...
;; ANSWER SECTION:
proxmost1.hmg.priv.	86400	IN	A	192.168.22.225

;; AUTHORITY SECTION:
hmg.priv.		86400	IN	NS	ns-1.grenet.fr.
hmg.priv.		86400	IN	NS	dns.hmg.inpg.fr.
```
**2) using bluebanquise name server running on the management node:**
```
bash-5.1$ dig @172.30.1.64 proxmost1.hmg.priv  A +nsid
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 30652
...
;; AUTHORITY SECTION:
.			9128	IN	SOA	a.root-servers.net. nstld.verisign-grs.com. 2025050800 1800 900 604800 86400
```

But testing another FDQN is working:
```
bash-5.1$ dig @172.30.1.64 google.com  A +nsid
;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		300	IN	A	172.217.18.238

;; Query time: 24 msec
;; SERVER: 172.30.1.64#53(172.30.1.64)
```

So may be something additional is needed to forward ALL unmanaged requests from bluebanquise DNS to my forwarder 194.254.66.12 ?

**Comment by patrick-begou** [comment]
Problem identified: it is a DNSSEC failure on the forwarder.
https://access.redhat.com/solutions/1400113
- disabling DNSSEC in bluebanquise nameserver solves temporarily the problem in /etc/named/named.conf.options
```  
forwarders {
    194.254.66.12;
  };

 # dnssec-validation auto;
  dnssec-enable no;
  dnssec-validation no;
```
Best solution is to have DNSSEC on the forwarder.

**Comment by oxedions** [comment]
Dear @patrick-begou 

Many thanks for this feedback and apologies for the delay of my last answer.
That would have been my second area of investigation, so super if you could fix it :slightly_smiling_face: 

Indeed, solution is to have DNSSEC on the forwader itself, for security reasons.

Let me know if you need any adaptation of the dns_server role :blush:

**Comment by pbirokas** [comment]
I just walk over this topic and wanted to add two things we added because we had running into the same problem:

1.) Deactivate the manage of DNS by Network-Manager:
```
  pre_tasks:
    - name: set NetworkManager variable 
      community.general.ini_file:
        path: /etc/NetworkManager/NetworkManager.conf
        section: main
        option: "{{ item.option }}"
        value: "{{ item.value }}"
        mode: '0644'
        backup: true
      loop:
        - { option: 'dns', value: "none" }
        - { option: 'rc-manager', value: "unmanaged" }
      tags: pre_tasks
```


2.) We added those two vars to the dns_server role
```
# management.yml
[...]
    - role: bluebanquise.infrastructure.dns_server
      vars:
       dns_server_dnssec_enable: no
       dns_server_dnssec_validation: no
[...]
```

**Reply by oxedions** [reply]
Dear @pbirokas 

I am very sorry for the delay of my answer. Just cant follow with my family life (young kids).

Would you accept to tell me why you deactivated DNS management by NetworkManager, and how you configured DNS then ? Via /etc/resolv.conf file ?
This is an important feedback because I wasnt sure what users really desired about that: /etc/resolv.conf or NM managing it (or allow both, choice do admin maybe ?)

**Reply by pbirokas** [reply]
Dear @oxedions,

The Ansible/Bluebanquise manages the file on the dns_client role.
But after every reboot or restart of NM, the NM overwrites the resolve.conf.
Any custom entries that has bees configured like additional search domains or external servers gets overwritten.

Thats why we deactivated the management of dns client by NM.

**Reply by oxedions** [reply]
Ok, this makes sens.
Many thanks :blush:

**Reply by oxedions** [reply]
Do you allow me to copy your code to improve the nic role ?

```
  pre_tasks:
    - name: set NetworkManager variable 
      community.general.ini_file:
        path: /etc/NetworkManager/NetworkManager.conf
        section: main
        option: "{{ item.option }}"
        value: "{{ item.value }}"
        mode: '0644'
        backup: true
      loop:
        - { option: 'dns', value: "none" }
        - { option: 'rc-manager', value: "unmanaged" }
      tags: pre_tasks
```
