### DISCUSSION TITLE
Define routes using a task

### DISCUSSION THREAD

**Discussion by oxedions** [bluebanquise/bluebanquise#443] [Q&A]
Hello 🙂 

I am working on the nmcli role.

I would write the nmcli full module. However, I have issues with routes.

Let me explain the thing:

Routes have to be defined using nmcli. For example:

```
nmcli connection modify enp0s8 +ipv4.routes "10.11.0.0/24 10.10.0.2, 10.12.0.0/24 10.10.0.2"
```

And I can query what are the current ipv4.routes on interface enp0s8 this way:

```
nmcli connection show enp0s8 | grep ipv4.routes
```

I tried to provide possible routes this way in the inventory:

```
        management1:
          bmc:
            name: bmanagement1
            ip4: 10.10.100.1
            mac: 08:00:27:dc:f8:f6
            network: ice1-1
          network_interfaces:
            - interface: enp0s8
              ip4: 10.10.0.1
              mac: 08:00:27:5b:76:25
              network: ice1-1
              routes4:
                - 10.11.0.0/24 10.10.0.2
                - 10.12.0.0/24 10.10.0.2
```

And also later have the possibility to define routes in the network.yml file, so if a NIC is connected to a network, it can use these (with priority to the ones under the interface over the ones in the network).

But I am not in a jinja2 template, but in a task, which makes things a bit complex 🙁 

I already tried this:

```
  - name: Gather routes
    shell: "nmcli connection show {{item.interface}}| grep ipv4.routes | awk -F ':' '{print $2}' | sed 's/\ ip\ =//g' | sed 's/,\ nh\ =//g' | sed 's/{//g' | sed 's/}//g'"
    loop: "{{ network_interfaces }}"
    when: item.interface is defined and item.ip4 is defined
    register: current_ipv4_routes
```

Which output in stdout of the register something like this for example:

```
    stdout: '                             10.11.0.0/24 10.10.0.2 ;  10.12.0.0/24 10.10.0.2 '
```

So I wanted to check with a loop over routes4 if all string are contain in this stdout string (is 10.11.0.0/24 10.10.0.2 in stdout ?), and if not execute an nmcli like above.

I could cross both loop (the register and network_interfaces) using product filter:

```
  - debug:
      msg: "{{ item[0].item.interface }} {{ item[1].interface }}"
    loop: "{{ current_ipv4_routes.results | product(network_interfaces) | list}}"
    when:
      - item[1].interface == item[0].item.interface
```

But then, how can I iterate at a third level over the route4 list... Do not know. I am probably not in the good way to do things.

I could say: if a route is defined, I always apply it. But this is not very clean...

Any idea ?
