### DISCUSSION TITLE
ssh_master and no attribute network_interfaces error

### DISCUSSION THREAD

**Discussion by patrick-legi** [bluebanquise/bluebanquise#479] [Cluster deployment] [answered]
Hi

Back to commit f73e52199c8fac93899992b9015dc1f0858a46be (HEAD -> master, origin/master, origin/HEAD)
```
Merge: f91d442 b921143
Author: Ox <oxedions@gmail.com>

Date:   Fri Nov 13 09:48:22 2020 +0100
```

The commande:
`# ansible-playbook /etc/bluebanquise/playbooks/managements.yml --tags ssh_master
`
Returns:
```
Friday 13 November 2020  12:54:31 +0100 (0:00:02.133)       0:00:02.277 ******* 
fatal: [management1]: FAILED! => changed=false 
  msg: 'AnsibleUndefinedVariable: ''ansible.vars.hostvars.HostVarsVars object'' has no attribute ''network_interfaces'''

```
But in /etc/bluebanquise/inventory/cluster/nodes I have just (for test) managements.yml with:
```
# cat managements.yml
mg_managements:
  children:
    equipment_typeM:
      hosts:
        management1:
          network_interfaces:
            - interface: ens19
              ip4: 172.30.1.1
              network: ice1-1
            - interface: ens18
              ip4: 194.254.66.20
              network: public-1
              gw4: 194.254.66.62

```
What is wrong with network_interfaces and this commit ? It works with older commit.

Patrick
