### DISCUSSION TITLE
firewall role help needed

### DISCUSSION THREAD

**Discussion by gauthierdelerce** [bluebanquise/bluebanquise#491] [Cluster deployment]
Hello,
I'm using the firewall to secure the external acces to login nodes.
I followed the instructions without success and need your help to understand what I did wrong.

My goal is to allow only ssh connection through a specific interface.
I added the firewall definition to the network in the inventory : 
```
  bb:
    subnet: 158.129.164.0
    prefix: 24
    netmask: 255.255.255.0
    broadcast: 158.129.164.255
    #dhcp_unknown_range: 172.16.199.0 172.16.199.200
    gateway: 158.129.164.1
    is_in_dhcp: false
    is_in_dns: false
    firewall:
      zone: backbone
    routes4:
      - ip = 0.0.0.0/0, nh = 158.129.164.1
```

and a firewall defintion :
```
 firewall_zones:
    - zone: backbone
      masquerade: false
      services_enabled:
        - ssh
```

A zone named backbone can not be used, therefore I used the external.

After applying the role, I observed the filtering is done on the IP address, therefore the rule doesn't apply for connection which are not coming for the subnet.
```
external (active)
  target: default
  icmp-block-inversion: no
  interfaces: 
  sources: 158.129.164.0/24
  services: ssh
```

I might be better to define the rule with the interface 

I also observed that the role add rules, but doesn't ensure the state of the firewall is the expected one.
IMHO if we remove a service from the firewall definition in ansible, it should be removed on the node too.

Thanks for your help

**Comment by btravouillon** [comment]
Hi @gauthierdelerce,

In this role, we bind a firewalld zone with a BlueBanquise network (*bb* in your example). Given the inventory structure, this is tricky to identify the correct network interface to use for a given host (while it might be easier with the changes to network_interfaces introduced with 1.3).

You can easily add your interface to any zone with the playbook below:
```
- name: firewall
  hosts: "mg_logins"
  pre_tasks:
    - name: Add ens5 to external zone
      firewalld:
        zone: external
        interface: ens5
        permanent: yes
        immediate: yes
        state: enabled

  roles:
    - role: firewall
      tags: firewall_role
```

Note this is not persistent across reboot due to a [known bug](https://github.com/ansible-collections/ansible.posix/issues/75).

**Reply by btravouillon** [reply]
If you don't want to use a predefined zone, you can create one:

```
- name: firewall
  hosts: "mg_logins"
  pre_tasks:
    - name: Create zone backbone
      firewalld:
        zone: backbone
        state: present
        permanent: yes
    - name: Reload firewalld
      service:
        name: firewalld
        state: restarted
    - name: Add ens5 to backbone zone
      firewalld:
        zone: backbone
        interface: ens5
        permanent: yes
        immediate: yes
        state: enabled

  roles:
    - role: firewall
      tags: firewall_role
```

```
# ssh login1 firewall-cmd --get-active-zones
backbone
  interfaces: ens5
public
  interfaces: ens6 ens7
  sources: 10.10.0.0/16 10.20.0.0/16
```

**Reply by btravouillon** [reply]
#499 to create a new zone with the role firewall.

**Comment by gauthierdelerce** [comment]
Hi Bruno,
Thanks a lot for the clear answer, it might be added in the README 
I'm a bit disappointed by the lost of rules after a reload/restart of firewalld, or a reboot; and I would suggest to ensure the sysadmin knows this if it uses this role.

In the mean time, is there any chance to patch the role to execute the command, from a shell ? As example : 
```
firewall-cmd --zone=backbone --change-interface=enp4s0.158 --permanent
firewall-cmd --zone=backbone --add-service=ssh --permanent

```

Would you consider to check the firewall status after the role execution or you consider bluebanquise purpose is to configure the cluster and not to check the configuration of the nodes is the same as the one define in ansible? ( example; we remove a service in a zone, run firewall role but the service is not removed on the node ) 

Thanks again for the quick and clear answer

**Reply by btravouillon** [reply]
> I'm a bit disappointed by the lost of rules after a reload/restart of firewalld, or a reboot; and I would suggest to ensure the sysadmin knows this if it uses this role.

So do I. I checked the code of the [firewalld module](https://docs.ansible.com/ansible/latest/collections/ansible/posix/firewalld_module.html), it does not handle the change of the zone for an interface as firewall-cmd do. The module makes use of the firewalld python libraries, while the firewalld-cmd fallbacks to NetworkManager to configure the zone of an interface. If no zone is defined for an interface with NetworkManager, firewalld assign this interface to the default zone at start.

> 
> In the mean time, is there any chance to patch the role to execute the command, from a shell ? As example :
> 
> ```
> firewall-cmd --zone=backbone --change-interface=enp4s0.158 --permanent
> firewall-cmd --zone=backbone --add-service=ssh --permanent
> ```
> 

No chance to patch the role **firewall** for the first command. In RHEL 8 (at least, I did not check other OS), the firewalld-cmd modifies the interface configuration with NetworkManager, since the zone is a property of the interface. I would follow the same logic and define the zone in network_interfaces.

```
mg_logins:
  children:
    equipment_typeL:
      hosts:
        login1:
          network_interfaces:
            - interface: ens5
              zone: backbone
```

With the current **nic** role, we could implement this quickly. It would be more difficult with the **nic_nmcli** role since, afaik, the connection.zone parameter is not supported yet.

The second command must be covered with the inventory snippet from your post:
```
 firewall_zones:
    - zone: backbone
      masquerade: false
      services_enabled:
        - ssh
```

> Would you consider to check the firewall status after the role execution or you consider bluebanquise purpose is to configure the cluster and not to check the configuration of the nodes is the same as the one define in ansible? ( example; we remove a service in a zone, run firewall role but the service is not removed on the node )

The purpose of the stack is to configure the target host as defined in the inventory, on top of the default OS configuration and previous configuration. If you configure your inventory to remove a service in a zone, the role **firewall** must remove this service from this zone. You need to explicitly remove the service from the zone. Removing a definition from the inventory (ie. deleting values from the inventory) is a different use-case for which the role cannot take action, since no configuration is given.

When you want to add a configuration, you explicitly define it in your inventory. If you want to remove it later, you have to explicitly define it as well.
