### DISCUSSION TITLE
Very slow ansible-core 2.14 when parsing inventory during task execution

### DISCUSSION THREAD

**Discussion by ginomcevoy** [bluebanquise/bluebanquise#837] [General]
Hello, I would like to share an observation we have on our deployments with ansible-core 2.14, and also ask if anybody else has observed this poor performance.

Starting with RHEL 8.8 (ansible-core 2.14.2), we have observed significantly slower performance coming from ansible, when parsing large inventories. For example, consider this task:

```
    - name: "Make sure group '{{ ibms.ibms_dedicated_group }}' exists"
      ansible.builtin.group:
        gid: "{{ ibms.ibms_dedicated_group_id }}"
        name: "{{ ibms.ibms_dedicated_group }}"
        system: yes
        state: present 
```
The task just needs to create a system group / check that a system group exists. Just the check can take up to **25 seconds** on a cluster with a large inventory (the cluster has less than 100 nodes, but it has large inventory files). Compare this to ansible-core 2.13.3 from RHEL 8.7, the same task takes less than 1 second. The task gets faster if we switch the jinja variables with constants.

Running the same task with smaller inventories can decrease the execution time, e.g. 7 seconds, 3 seconds. But still these numbers are about one order of magnitude larger than the original execution time.

I have checked the ansible github, and there are similar performance issues, but I did not find an exact fit. There are some issues with slowness in "ansible all --list-hosts" or even "ansible-inventory --list --output /dev/null", but these are all fast in our cluster. It's the parsing during task execution that is slow.

Has anybody else noticed a similar issue? We have experimented with with newer versions of ansible (ansible 8.3.0, ansible-core 2.15.3) and performance is about similar (poor).

I can try to create a reproduceable minimal example to show the slowness on this task and open an issue in ansible, but it looks like they are not prioritizing performance issues.
