### DISCUSSION TITLE
Split equipment groups

### DISCUSSION THREAD

**Discussion by oxedions** [bluebanquise/bluebanquise#849] [Ideas]
# 2.X to 3.X major changes

@sla31 came with a very interesting proposal: split current `ep_` groups into 2 entities: `hw_` and `os_`, as more and more clusters are mixing OS on same hardware.
A change like that right now would immediately end 2.X devs and focus on releasing an upgraded 2.X version that would be a 3.X due to this very intrusive change.

### Groups split

Objective: split current `ep_` groups into 2, `hw_` and `os_` because it often happen that a cluster have same kind of server with mutliple kind of OS profiles (RHEL 8 and RHEL 9 at the same time, Ubuntu and RHEL, etc).
Having 2 layers, aka hardware and OS, would ease usage and swap of servers OS profiles while being able to retain hardware profile. It also helps distribute hardware pre-made profiles.

This is similar to: IaaS (infrastructure = HW), PaaS (platform = OS), SaaS (service = application)

BlueBanquise Infrastructure collection will cover IaaS and PaaS, while other collections whould provide SaaS.

Constraints:
- keep retro-compatibility when possible with previous `ep_` variables, using precedence piping mechanism (os and hw win againts ep).
- Prevent authentication related variables (mainly BMC password and co) to be used as `groups("stuf")[0]` to allow hostvars level usage (due to more and more BMC having dedicated credentials). (Prometheus identified as impacted)

### Rename mg_ groups

Need a new name as "master groups" is not really clear. "Roles" would be nice but conflicts with Ansible roles.
Purpose ? Function ? Profile ? To be determined. These groups will become more important as they will be used for playbooks in toolings.

### Groups split

* `os_partitioning` > `ep_partitioning` > `hw_disks`
`hw_disks` being a specific mechanisme that can auto-populate automated install files. `os_partitioning` and former `ep_partitioning` are raw content.

* `hw_consoles` is a list
In iPXE templates: ```"set eq-console {{ ['console='] | product( (['tty0','tty1'] + hw_consoles) | unique ) | map('join') | join(' ') }}"```

* New `hw_architecture`, to define CPU arch, will be needed in some specific roles.
Document possibility to retro compatible with ```"ep_hardware.cpu.architecture: {{ hw_architecture }}"```

* `ep_hardware` to be renamed `hw_specs` and that contains hardware definition. Be extra precise this time with format, as it will be used by many roles now.

* `ep_host_authentication` to be renamed, like `hw_mgmt_authentication` or `hw_board_communication` or `hw_communication_protocol` or similar. To be defined but have to be clear it is not OS related (not os password).

* `hw_kernel_parameters` should be available along `os_kernel_parameters` as both could be used (some specific parameter linked to hardware, and then another one related to a specific OS). ```set eq-kernel-parameters {{ nodevars['hw_kernel_parameters'] | default('') }} {{ nodevars['os_kernel_parameters'] | default('') }}```

* `ep_equipment_type` become `hw_equipment_type`, provide a list as standard but allow custom values.

* `pxe_stack_node_main_network_interface` has disapear, blame and investigate why, and fix this.

* `os_extra_install_repos` and `os_packages_to_install_with_os_install` or similar to add to pxe_stack role.

* `ep_autoinstall_custom_content` to be renamed os_...

All other `ep_` variables have to be sorted between `os_` and `hw_` groups.

This needs to add new j2 variables, like but not only:

```
bb_core_hw_naming: hw
bb_core_os_naming: os 

j2_hw_groups_list: "{{ groups | select('match','^'+bb_core_hw_naming+'_.*') | list | unique | sort }}"

j2_os_groups_list: "{{ groups | select('match','^'+bb_core_os_naming+'_.*') | list | unique | sort }}"
```

Also, add a small and quick validation role, that scan hosts to check if they belong to both an os_ group and an hw_ group. Check if it does not conflicts with current BB 2.X since this version allows to simplify cluster using a single all group with roles dedicated variables.

**Comment by sla31** [comment]
The PXE profile of a node may be determined as follows:
```jinja
j2_ep_groups: "{{ groups | select('match','^'+bb_core_equipment_naming+'_.*') | list | unique | sort }}"

j2_pxe_profile: "
{%- set ep_groups = group_names | select('match', '^'+bb_core_equipment_naming+'_.*') | list | sort %}
{%- set ep_grp_count = ep_groups | length %}
{%- if ep_grp_count > 1 %}
  {{ undefined | mandatory('Host ' + inventory_hostname + ' belongs to multiple (' ~ ep_grp_count ~ ') EP groups: ' + ep_groups | join(' + ')) }}
{%- endif %}
{%- set hw_groups = group_names | select('match', '^'+bb_core_hw_naming+'_.*') | list | sort %}
{%- set hw_grp_count = hw_groups | length %}
{%- if hw_grp_count > 1 %}
  {{ undefined | mandatory('Host ' + inventory_hostname + ' belongs to multiple (' ~ hw_grp_count ~ ') HW groups: ' + hw_groups | join(' + ')) }}
{%- endif %}
{%- set os_groups = group_names | select('match', '^'+bb_core_os_naming+'_.*') | list | sort %}
{%- set os_grp_count = os_groups | length %}
{%- if os_grp_count > 1 %}
  {{ undefined | mandatory('Host '+ inventory_hostname + ' belongs to multiple (' ~ os_grp_count ~ ') OS groups: ' + os_groups | join(' + ')) }}
{%- endif %}
{%- if hw_grp_count == 1 and os_grp_count == 1 and ep_grp_count == 0 %}
  {%- set hw_grp = hw_groups | first | regex_replace('^'+bb_core_hw_naming+'_', '') | trim %}
  {%- set os_grp = os_groups | first | regex_replace('^'+bb_core_os_naming+'_', '') | trim %}
  {{- hw_grp }}-{{ os_grp }}
{%- elif hw_grp_count == 0 and os_grp_count == 0 and ep_grp_count == 1 %}
  {%- set ep_grp = ep_groups | first | regex_replace('^'+bb_core_equipment_naming+'_', '') | trim %}
  {{- ep_grp }}
{%- else %}
  {{- undefined | mandatory('Inconsistent group membership for host ' + inventory_hostname + ': ' + (ep_groups+hw_groups+os_groups) | join(' + ')) }}
{%- endif -%}
"
```
That piece of code not only determines the PXE profile of a node, but also checks whether the user created a consistent inventory:

- either exactly one HW group and exactly one OS group (not 2 or more HW or OS groups for each node)
- (exclusive) or exactly one EP group per node

> Also, add a small and quick validation role, that scan hosts to check if they belong to both an os_ group and an hw_ group

Of course, that code may be split in its 2 functions:

- determine the PXE profile of a node with no check and inconsistency reporting
- check consistency (in a validation role) → either we're strict on consistency (as in the code above), or we're using precedence (HW/OS > EP).

> keep retro-compatibility when possible with previous ep_ variables, using precedence piping mechanism (os and hw win againts ep).

The `pxe_stack` role needs the list of PXE profiles, which may be derived either from the HW/OS groups, or from the EP group for backward compatibility.  The list of PXE profiles may be determined as follows:
```jinja
j2_pxe_profiles: "
{%- set ns=namespace(profiles={}) %}
{%- for node in hostvars | dict2items | selectattr('value.os_specification', 'defined') | map(attribute='key') %}
  {%- set prfl = hostvars[node]['j2_pxe_profile'] %}
  {%- set ns.profiles = ns.profiles | combine({ prfl : node }) %}
{%- endfor %}
{{- ns.profiles -}}
"
```
(here, `os_specification` is just another name for `ep_operating_system`).

The `j2_pxe_profiles` is a dict like:
```yaml
j2_pxe_profiles:
  dgx1-dgxos_5: dgx1
  r423_e4i-ubuntu_20_04: node04
  r423_e4m_efi-rhel_9_2: node01
  r423_e4m_efi-ubuntu_20_04: node02
  r424_f3-ubuntu_20_04: master04
  x430_a5_sw_raid-ubuntu_20_04: popserver04
  x430_e5-ubuntu_20_04: node03
  x440_a5_diskless-rhel_9_2: node08
```
The keys of the dict are:

- either the EP group name radix
- or the HW group name radix, followed by the dash symbol (`-`), followed by the OS group name radix

The values are the name of one of the hosts which belong to that PXE profile (either the EP group, or the combination of the HW & OS groups).  This is to hide this trick in the `pxe_stack` role: `groups[item][0]` (would be replaced with `pxe_profiles[item]` which is a bit faster to execute).

Defining those variables makes the required updates to the `pxe_stack` role straightforward.

🚨: for performance, avoid using those 2 variables (`j2_pxe_profile` of a node, and `j2_pxe_profiles`) in loops where they are used (and evaluated as macros) multiple times.  Better set a fact once for all at the beginning of the `pxe_stack` role:
```yaml
ansible.builtin.set_fact:
  pxe_profiles: "{{ j2_pxe_profiles }}"
```
(in my test environment with few nodes but many HW & OS groups, the `pxe_stack` role takes 250+ seconds without `set_fact`, and 30 seconds with `set_fact`)

More later...

**Comment by sla31** [comment]
> `hw_disks` being a specific mechanism that can auto-populate automated install files. `os_partitioning` and former `ep_partitioning` are raw content

`hw_disks` is meant to describe how the drives are to be partitioned/formatted/mounted/used in a Linux distribution agnostic manner, by using a simple YAML syntax which is independent of the cloud-init syntax (for Ubuntu), PreSeed syntax (for Debian), XML AutoYaST syntax (for SUSE), or KickStart syntax (for RedHat and friends).  That simple YAML description of partitioning is then translated by the `pxe_stack` role in its KickStart/cloud-init/etc. templates, depending on the Linux distribution specified in the OS group.

`hw_disks` is superseded by `os_partitioning` and `ep_partitioning`, which are copied verbatim ("raw content") to the KickStart configuration file, or cloud-init config file (for Ubuntu), or Debian PreSeed, etc.  That's useful is case the simple YAML description supported by `hw_disks` is too simple to express the sophisticated partitioning required by the user.  Even though the syntax of `hw_disks` is simple, I believe it covers most cases.

The benefit of that distribution-agnostic `hw_disks` description is that the same servers (same hardware, same partitioning) can belong to the same, unique HW group, but be deployed with different Linux distribs depending on what OS group they belong to.  So changing the Linux distribution of a server is just a matter of changing its OS group, without the user having to re-write the partitioning stanzas for yet another Linux distrib.

Here are a few examples illustrating the `hw_disks` syntax, as a proposal.

### Simplest partitioning for a UEFI platform

- `/boot/efi` partition of 1GB (default) with flag ESP and format vFAT
- root file-system `/` taking the rest of the storage space on the disk, with format XFS
```yaml
hw_disks:
- drives:
    /dev/sda:
  partitions:
    /:
    efi:
```

### Simplest partitioning for a BIOS platform

- the BIOS boot partition required for BIOS platforms using GPT (to install the boot loader), size 1MiB (default)
- root file-system / taking the rest of the storage space on the disk, with format XFS
```yaml
hw_disks:
- drives:
    /dev/sda:
  partitions:
    /:
    biosboot:
```

### Complete, commented example
```yaml
hw_disks:
- raid_level: 1 # Software RAID level
  drives:
    /dev/nvme2n1:
    /dev/nvme3n1:
  partitions:
    /:
    efi:
- drives: # No RAID level specified → no software RAID (may be hardware RAID, does not matter here), only one drive allowed in this list
    /dev/sda:
      path: "/dev/disk/by-path/pci-0000:18:00.0-scsi-0:0:11:0" # Optional - Used by the RedHat installer only
      device: "/devices/pci0000:17/0000:17:02.0/0000:18:00.0/host0/target0:0:11/0:0:11:0/block/sda" # Optional - Used by Ubuntu installer only
      model: "SAMSUNG_MZ7KH480" # Optional - Used by Ubuntu installer only
  partitions:
    /tmp:
      size: 10240 # Optional - unit = MiB - rest of the storage space if omitted
      fstype: ext4 # Optional - XFS if omitted
    swap: # fstype is optional - fstype=swap if omitted - only supported value is 'swap'
      size: 4096
    /home: # No size specified → rest of the available storage space # No fstype specified: XFS by default
- raid_level: 0 # Software RAID level
  drives:
    /dev/nvme0n1:
      model: "KCM6DRUL3T84"
    /dev/nvme1n1:
      model: "KCM6DRUL3T84"
    /dev/nvme4n1:
      model: "KCM6DRUL3T84"
    /dev/nvme5n1:
      model: "KCM6DRUL3T84"
  partitions:
    /scratch: # Use total storage space # XFS format by default
```
Supported `fstype`: xfs, ext4, ext3, ext2, swap (only supported for the SWAP partition), vfat (or fat32), efi (only supported for the EFI special partition), biosboot (mutually exclusive with EFI).
Because of a limitation in Curtin (to install Ubuntu), only unpredictable drive paths are supported (like `/dev/sda`), while predictable drive paths are supported by KickStart for RHEL (like `/dev/disk/by-path/...`).  So the keys under the `drives` dict are the unpredictable drive paths for the moment if the user want to support both distributions.  Under that dictionary keys are supported the following additional fields:

- `path`: the optional predictable drive path (`/dev/disk/by-path/...`) which is used to generate the partitioning description for KickStart only (if defined, the predictable drive path supersedes the unpredictable path)
- `device` & `model`: optional fields only used to generate the cloud-init partitioning description (Ubuntu), so as to ensure that the unpredictable drive path is really the intended disk (see section [Top-level keys → storage → Action-based config → Disk selection extensions](https://ubuntu.com/server/docs/install/autoinstall-reference))

## Limitations:

- only GPT partition tables are supported here (we're in the 21st century, most platforms are UEFI now!) → no "msdos" partition tables with `hw_disks` ("msdos" partition tables are still possible with raw `os_partitioning` or `ep_partitioning`)
- does not expose all the partitioning features permitted by KickStart or by Curtin or by ... (but covers most reasonable cases)

More later...
