### DISCUSSION TITLE
[Resolved] What are the possible values for j2_bb_nodes_profiles or bb_nodes_profiles?

### DISCUSSION THREAD

**Discussion by sgaosdgr** [bluebanquise/bluebanquise#855] [Cluster deployment]
I searched entire repo and could not find any example or explanation about what values can be set for j2_bb_nodes_profiles or bb_nodes_profiles.  Are the values, diskful, diskless. This variable is referenced in pxe_stack and slurm roles.   

It does not seem to do much:

```
# Roles transverse variables caching
- name: fact <|> Calculate bb_nodes_profiles
  ansible.builtin.set_fact:
    bb_nodes_profiles: "{{ j2_bb_nodes_profiles }}"
  when: bb_nodes_profiles is not defined or bb_nodes_profiles is none
  tags:
    - templates

- name: debug <|> Display bb_nodes_profiles
  ansible.builtin.debug:
    msg: "{{ bb_nodes_profiles}}"
```

Any help is appreciated.

**Comment by sgaosdgr** [comment]
Same question for j2_bb_equipments. What values are available for this variable?

```
- name: fact <|> Calculate bb_equipments
  ansible.builtin.set_fact:
    bb_equipments: "{{ j2_bb_equipments }}"
  when: bb_equipments is not defined or bb_equipments is none
  tags:
    - templates

- name: debug <|> Display bb_equipments
  ansible.builtin.debug:
    msg: "{{ bb_equipments}}"
```
