### ISSUE TITLE
[FEATURE REQUEST] hosts_file role - allow the FDQN to be set first in /etc/hosts.

### ISSUE THREAD

**Issue by levaillx** [bluebanquise/bluebanquise#1005]
Allow the FDQN to be set first in /etc/hosts.

## Possible fix

bluebanquise-3.1.1/collections/infrastructure/roles/hosts_file/defaults/main.yml
```
@@ -2,6 +2,7 @@
 hosts_file_domain_name:
 hosts_file_external_hosts: {}
 hosts_file_range: iceberg
+hosts_file_fqdn_first: false

 # Allow to write all host names
 # If set to true, hostname, alias, nic-network and nic-alias will be written info hosts file
```

bluebanquise-3.1.1/collections/infrastructure/roles/hosts_file/templates/hosts.j2
```
@@ -13,7 +13,11 @@
   {% endif %}

   {%- if host_j2_node_main_resolution_address is not none and (host_j2_node_main_resolution_address | ansible.utils.ipaddr) %}
+    {% if hosts_file_fqdn_first %}
+{{ host_j2_node_main_resolution_address }} {{ host }}.{{ hosts_file_domain_name | default(bb_domain_name, true) | default('cluster.local', true) }} {{ host }} {{ alias_list | join(' ') }}
+    {% else %}
 {{ host_j2_node_main_resolution_address }} {{ host }} {{ host }}.{{ hosts_file_domain_name | default(bb_domain_name, true) | default('cluster.local', true) }} {{ alias_list | join(' ') }}
+    {% endif %}
   {% endif -%}

   {%- if hosts_file_enable_extended_names %}
```
