### ISSUE TITLE
An wrong ifcfg file is generate even no ip is set in the nic declaration

### ISSUE THREAD

**Issue by loar38** [bluebanquise/bluebanquise#101]
We need to declare a nic in a new network but we can't set an IP as the IP will be mamanged by kubernetes.
I tried addind a test to skipped the ifcfg generation if no ipv4 is set in the role nic 
For example

```
- name: Set NIC configuration
  template:
    src: ifcfg.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-{{item}}
    owner: root
    group: root
    mode: 0644
  with_items: "{{network_interfaces}}"
  when: (network_interfaces[item]['ip4'] is defined and not none)
```
without the test, an ifcfg file is generate but with empty parameter.
