### ISSUE TITLE
[FEATURE REQUEST] restart NetworkManager

### ISSUE THREAD

**Issue by vedmonds** [bluebanquise/bluebanquise#1114]
https://github.com/bluebanquise/bluebanquise/blob/af6048955b1fc33d378be3be52e1a0a0e07bf0e8/collections/infrastructure/roles/nic/tasks/main.yml#L24

If a newer version of nmcli is installed then NetworkManager needs to be restarted 

## Context

If we newer version of nmcli is installed but NetworkManager is not restarted, then the role fails when it attempts to modify network settings via nmcli at this task
https://github.com/bluebanquise/bluebanquise/blob/af6048955b1fc33d378be3be52e1a0a0e07bf0e8/collections/infrastructure/roles/nic/tasks/nmcli.yml#L22

## Feature

Add a notify statement and related handler to restart the NetworkManager service

`collections/infrastructure/roles/nic/tasks/main.yml`
```
- name: "package <|> Install {{ nic_packages_to_install | join(' ') }}"
  ansible.builtin.package:
    name: "{{ nic_packages_to_install }}"
    state: present
  tags:
    - package
  notify: service <|> Restart nic services

- name: "service <|> Start services"
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: yes
    state: "{{ (nic_start_services | bool) | ternary('started', omit) }}"
  loop: "{{ nic_services_to_start }}"
  tags:
    - service

- name: meta <|> Run handler tasks to apply OS dedicated events
  ansible.builtin.meta: flush_handlers
```

`collections/infrastructure/roles/nic/handlers/main.yml`
```
- name: "service <|> Restart nic services"
  ansible.builtin.service:
    name: "{{ item }}"
    state: "{{ (nic_start_services | bool) | ternary('restarted', omit) }}"
  loop: "{{ nic_services_to_start }}"
  tags:
    - service
```
