### ISSUE TITLE
[BUG] time role ignore os_firewall setting and always treat it as true

### ISSUE THREAD

**Issue by sgaosdgr** [bluebanquise/bluebanquise#1115]
[Provide general introduction to the issue logging and why it is relevant to this repository.]

For role, time, https://github.com/bluebanquise/bluebanquise/tree/master/collections/infrastructure/roles/time

Task, tasks/RedHat/firewall.yml, has a condition `os_firewall`, which does not work as expected inside a loop even when `os_firewall` is set to false.

Here are current codes:

```
 - name: firewalld <|> "Add services to firewall's {{ time_firewall_zone | default('public') }} zone"
  ansible.posix.firewalld:
    zone: "{{ time_firewall_zone | default('public') }}"
    service: "{{ item }}"
    immediate: "yes"
    permanent: "yes"
    state: enabled
  when:
    - os_firewall | default(false) | bool
  loop: "{{ time_firewall_services_to_add }}"
  tags:
    - firewall
 ```

## Process

1.  Set `os_firewall` to false for a node
2.  Apply role `time`.

## Expected result

The firewall task should skip

## Current result

The firewall task fails when firewalld is not running.

```
TASK [bluebanquise.infrastructure.time : firewalld <|> "Add services to firewall's public zone"] ***
337
failed: [compute-0-2] (item=ntp) => changed=false 
338
  ansible_loop_var: item
339
  item: ntp
340
  msg: firewall is not currently running, unable to perform immediate actions without a running firewall daemon
```
## Possible Fix

Change the task as follow:

```
- name: Add ntp service to firewall when os_firewall set to true
  tags:
    - firewall
  when:
    - os_firewall | default(false) | bool
  block:
    - name: firewalld <|> "Add services to firewall's {{ time_firewall_zone | default('public') }} zone"
      ansible.posix.firewalld:
        zone: "{{ time_firewall_zone | default('public') }}"
        service: "{{ item }}"
        immediate: "yes"
        permanent: "yes"
        state: enabled
      loop: "{{ time_firewall_services_to_add }}"
```

## Additional data

When os_firewall is set to false, entire block is skipped.
