### ISSUE TITLE
Issue with OS variables gathering and variable precedence

### ISSUE THREAD

**Issue by actatux** [bluebanquise/bluebanquise#205]
Hello,

I started to change the way to gather OS variables in roles with #173 and #179, then put the work on hold:
> Comment on #173 fix: use with_first_found to gather OS vars
> By the way @actatux  
> I would like to not update more roles with this enhancement.  
> I would like to see how users react to this now :-)

We currently have some variable precedence issues because of these changes.

When running a playbook with a debug task, we can see the following:
```
# /usr/bin/ansible-playbook /etc/bluebanquise/playbooks/management1.yml \
    --extra-vars target=management1 --tags dns_server,time
[...]
TASK [time : DBG - Display value of 'packages_to_install'] ****************************
ok: [management1] => 
  msg:
  - bind

TASK [time : Install packages] ********************************************************
fatal: [management1]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable.
    The error was: 'list object' has no attribute 'centos'
```
The role time fails to install the packages. `packages_to_install = bind` because it was defined in the playbook scope by include_vars in the dns_server role, even if `packages_to_install` is also defined in time/vars/main.yml.

Obviously if we run the role individually, there is no issue:
```
# /usr/bin/ansible-playbook /etc/bluebanquise/playbooks/management1.yml \
    --extra-vars target=management1 --tags time
[...]
TASK [time : DBG - Display value of 'packages_to_install'] ****************************
ok: [management1] => 
  msg:
    centos:
      _7:
      - chrony
      _8:
      - chrony
    redhat:
      _7:
      - chrony
      _8:
      - chrony
    ubuntu:
      _18:
      - chrony
      - tzdata
```

 Extract of [Ansible documentation](https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#ansible-variable-precedence):

> Here is the order of precedence from least to greatest (the last listed variables winning prioritization):
> [...]
> 15. role vars (defined in role/vars/main.yml)
> [...]
> 18. include_vars
> [...]

We need to decide if we move forward or revert the changes before next release. An option could be to prefix the variables with role names (eg. dns_server_packages_to_install).
