### ISSUE TITLE
conman: ''dict object'' has no attribute ''authentication''

### ISSUE THREAD

**Issue by actatux** [bluebanquise/bluebanquise#216]
There is a mismatch between the role conman and the example inventories:
```
# sh tools/bluebanquise-playbook -p management1 --tags conman
[...]
TASK [conman : Template >> /etc/conman.conf] *********************************
fatal: [management1]: FAILED! => changed=false 
  msg: 'AnsibleUndefinedVariable: ''dict object'' has no attribute ''authentication'''
```
The template expects `hostvars[host]['equipment_profile']['authentication']['equipment_user']` and `hostvars[host]['equipment_profile']['authentication']['equipment_password']`.

In the examples inventory:
```
equipment_profile:
  equipment_authentication: # login/password for BMC, storage bay controller, switch, etc.
    user: ADMIN
    password: ADMIN
```

I would fix the template, I do prefer the syntax in the inventory. Any thought?
