### ISSUE TITLE
Clean repositories_client role

### ISSUE THREAD

**Issue by bouriquet** [bluebanquise/bluebanquise#258]
**Clean repositories_client role** :
- use /etc/dnf/vars instead of /etc/yum/vars
- do not generate empty environment file when the variable is not defined

Current code (roles/repositories_client/tasks/redhat_8.yml)
```
- name: template █ Generate /etc/yum/vars/environment to set $environment
  template:
    src: environment.j2
    dest: /etc/yum/vars/environment
    owner: root
    group: root
    mode: 0644
  tags:
    - template
```

Suggestion (roles/repositories_client/tasks/redhat_8.yml) :
```
- name: Set baseurl prefix
  set_fact:
    baseurl_prefix: "http://{{ networks[j2_node_main_network]['services_ip']['repository_ip'] }}/repositories/{{ equipment_profile.operating_system.repositories_environment is defined | ternary('$environment/', '') }}{{ equipment_profile['operating_system']['distribution'] }}/$releasever/$basearch/"

- name: template █ Generate /etc/yum/vars/environment to set $environment
  template:
    src: environment.j2
    dest: /etc/dnf/vars/environment
    owner: root
    group: root
    mode: 0644
  when: equipment_profile.operating_system.repositories_environment is defined
  tags:
    - template

- name: file █ Cleanup $environment
  file:
    path: /etc/dnf/vars/environment
    state: absent
  when: equipment_profile.operating_system.repositories_environment is not defined
  tags:
    - template
```
Suggestion (roles/core/repositories_client/templates/environment.j2) :
`{{ equipment_profile.operating_system.repositories_environment }}`

**Another minor issue** : environment / release vars customization are not documented either in the role or in the documentation (only a comment in group_vars/all/all_equipments/equipment_profile.yml)
