### ISSUE TITLE
Repositories client role should handle both repositories formats for Centos

### ISSUE THREAD

**Issue by oxedions** [bluebanquise/bluebanquise#288]
repositories_client role in core do not handle both repositories formats, aka:
```

  repositories:
    - os
    - bluebanquise
    - name: epel
      baseurl: 'https://dl.fedoraproject.org/pub/epel/$releasever/$basearch/'
      proxy: 'https://proxy:8080'
```

In the disable distribution repositories section of the task.
