### ISSUE TITLE
slurm - no test named 'None'

### ISSUE THREAD

**Issue by btravouillon** [bluebanquise/bluebanquise#332]
## Description

There is a typo in the slurm.conf template:
```
TASK [template █ Generate /etc/slurm//slurm.conf] ******************
Saturday 22 August 2020  22:24:41 +0200 (0:00:01.572)       0:00:20.370 ******* 
fatal: [management1]: FAILED! => changed=false 
  msg: |-
    AnsibleError: template error while templating string: no test named 'None'. String: #### Blue Banquise file ####
    ## {{ansible_managed}}
[...]
    {% if slurm['MpiDefault'] is defined and slurm['MpiDefault'] is not None %}
    ## Using pmi/pmi2/pmix interface for MPI
    MpiDefault={{slurm['MpiDefault']}}
    {% endif %}
[...]
```

## Inventory
```
# cat inventory/group_vars/all/slurm.yml 
---
slurm:
  slurm_packaging: after_17
  cluster_name: bluebanquise
  control_machine: management1
  #MpiDefault: pmi2 # Optional
  nodes_equipment_groups:
    - equipment_typeC
```

## Info
BlueBanquise 1.3-RC2
CentOS Linux release 8.2.2004 (Core) 
ansible 2.9.11
python 3.6.8

## Workaround

```
diff --git a/roles/addons/slurm/templates/slurm.conf.j2 b/roles/addons/slurm/templates/slurm.conf.j2
index 1780caf..ba1c0e0 100644
--- a/roles/addons/slurm/templates/slurm.conf.j2
+++ b/roles/addons/slurm/templates/slurm.conf.j2
@@ -31,7 +31,7 @@ SlurmdTimeout=600
 ## We don't want a node to go back in pool without sys admin acknowledgement
 ReturnToService=0
 
-{% if slurm['MpiDefault'] is defined and slurm['MpiDefault'] is not None %}
+{% if slurm['MpiDefault'] is defined and slurm['MpiDefault'] is not none %}
 ## Using pmi/pmi2/pmix interface for MPI
 MpiDefault={{slurm['MpiDefault']}}
 {% endif %}
```

## Note

I noticed a glitch we could fix in the same PR:
```
TASK [package █ Install ['munge', 'munge-libs', 'slurm', 'slurm-devel', 'slurm-slurmctld']]
```
