### ISSUE TITLE
[FEATURE REQUEST] Add more playbook examples in bluebanquise/resources/examples/simple_cluster/playbooks/

### ISSUE THREAD

**Issue by strus38** [bluebanquise/bluebanquise#375]
It would be interesting to provide more examples in bluebanquise/resources/examples/simple_cluster/playbooks/ to speed up basic tests of addon capabilities:

```
cat playbooks/addons.yml
---
- name: addons roles to run everywhere
  hosts: "mg_managements,mg_computes,mg_logins"
  roles:
    - role: root_password
      tags: root_password
    - role: prometheus_client
      tags: prometheus_client

- name: addons roles to run on management nodes
  hosts: "mg_managements"
  roles:
    - role: clustershell
      tags: clustershell

- name: addons roles to run on mngt1 only
  hosts: "management1"
  roles:
    - role: conman
      tags: conman
    - role: diskless
      tags: diskless
    - role: prometheus_server
      tags: prometheus_server

# cat playbooks/logs.yml
---
- name: log server playbook
  hosts: "management1"
  roles:
    - role: log_server
      tags: log_server

- name: log clients playbook
  hosts: "mg_computes,mg_logins,management2"
  roles:
    - role: log_client
      tags: log_client
```
