### ISSUE TITLE
ssh_master : template █ Generate /root/.ssh/config fail

### ISSUE THREAD

**Issue by btravouillon** [bluebanquise/bluebanquise#418]
# Description

The playbook fails at task `ssh_master : template █ Generate /root/.ssh/config`:

```
fatal: [management1]: FAILED! => changed=false
  msg: |-
    AnsibleError: template error while templating string: expected token '=', got '.'. String:
[...]
```

This is a fresh deployment with bluebanquise-vagrant. I'm running ansible for the first time to configure the management node.

# Info

OS: CentOS 7.8
Branch: master

# Reproducer

My playbook:
```
# cat playbooks/managements.yml
---
- name: managements playbook
  hosts: "management1"
  roles:
    - role: bluebanquise
      tags: bluebanquise

- name: managements playbook
  hosts: "mg_managements"
  roles:

    - role: set_hostname
      tags: set_hostname
    - role: nic
      tags: nic
    - role: repositories_server
      tags: repositories_server
    - role: repositories_client
      tags: repositories_client
    - role: firewall
      tags: firewall
    - role: hosts_file
      tags: hosts_file
    - role: ssh_master
      tags: ssh_master
    - role: dhcp_server
      tags: dhcp_server
    - role: advanced_dns_server
      tags: ['dns', 'dns_server']
    - role: dns_client
      tags: ['dns', 'dns_client']
    - role: time
      tags: time
      vars:
        time_profile: server
    - role: pxe_stack
      tags: pxe_stack
    - role: nfs_server
      tags: nfs_server

  tasks:
    - package:
        name: vim
        state: present
```

Command:
```
[root@management1 bluebanquise]# ansible-playbook playbooks/managements.yml -l management1
[...]
TASK [ssh_master : template █ Generate /root/.ssh/config] *****************************************************
Thursday 15 October 2020  22:10:37 +0000 (0:00:00.516)       0:00:09.047 ******
fatal: [management1]: FAILED! => changed=false
  msg: |-
    AnsibleError: template error while templating string: expected token '=', got '.'. String:
    {% macro node_main_network(macro_network_interfaces,macro_current_iceberg_network) %}
    {{ macro_network_interfaces | selectattr('network','defined') | selectattr('network','match','^'+macro_current_iceberg_network+'-[a-zA-Z0-9]+') | map(attribute='network') | list | first }}
    {% endmacro %}

    {# Macro to avoid redundancy #}
    {% macro write_host(host,macro_node_main_network,ssh_jump) %}
    Host {{ host }}
        {% if security.ssh.hostkey_checking is not defined or
              security.ssh.hostkey_checking == false %}
        StrictHostKeyChecking no
        UserKnownHostsFile=/dev/null
        {% endif %}
        {% if ssh_jump is none %}
        Hostname %h-{{ macro_node_main_network }}
        {% else %}
        Hostname %h
        ProxyJump {{ ssh_jump }}
        {% endif %}
    {% endmacro %}
    #### Blue Banquise file ####
    ## {{ ansible_managed }}

    {% if icebergs_system == true %}
    # Icebergs system is on
    {% set range = groups[j2_current_iceberg] %}
      {% for host in groups[managements_group_name] %}
        {% if hostvars[host]['iceberg_master'] == j2_current_iceberg %}
    {{ range.append(host) }}
        {% endif %}
      {% endfor %}
    {% else %}
      {% set range = groups['all'] %}
    {% endif %}

    {% for host in range %}
    {{ write_host(host,(node_main_network(hostvars[host]['network_interfaces'],j2_current_iceberg_network)| trim), None) }}
    {% endfor %}

    {% if icebergs_system == true and ssh_master_enable_jump == true %}
    # Icebergs ssh_jump system is on

    {#
    This mechanism allows SSH ProxyJump from a top iceberg to a sub_iceberg
    using one sub_iceberg management node to reach all other nodes in this sub_iceberg.
    Template will try to check if a manually set target has been set for the iceberg
    before using the first management node found in the group list.
    #}
      {% for iceberg in (groups | select('match','^'+iceberg_naming+'.*') | list | unique | sort ) %}
        {% if hostvars[groups[iceberg][0]]['iceberg_master'] == j2_current_iceberg %}
          {% set ssh_jump_target = namespace(value=none) %}
          {% if hostvars[groups[iceberg][0]]['ssh_master_iceberg_jump_target'] is defined %}
            {% set ssh_jump_target.value = hostvars[groups[iceberg][0]]['ssh_master_iceberg_jump_target'] %}
          {% else %}
            {% for host in groups[managements_group_name] %}
              {% if host in groups[iceberg] %}
                {% set ssh_jump_target.value = host %}
                {% break %}
              {% endif %}
            {% endfor %}
          {% endif %}
          {% if ssh_jump_target.value is not none %}

    ## Iceberg {{ iceberg }}
            {% for host in groups[iceberg] %}
              {% if host != ssh_jump_target.value %}
    {{ write_host(host, None, ssh_jump_target.value) }}
              {% endif %}
            {% endfor %}
          {% endif %}

        {% endif %}
      {% endfor %}

    {% endif %}

PLAY RECAP ***********************************************************************************************************
management1                : ok=18   changed=0    unreachable=0    failed=1    skipped=5    rescued=0    ignored=0
```
