### ISSUE TITLE
Diskless pre_tasks are not played if using flag --tags in ansible-playbook command

### ISSUE THREAD

**Issue by gavillom** [bluebanquise/bluebanquise#420]
Hi,

I'm trying to customize a diskless with Ansible roles. If I just want to replay a role with --tags flag, pre_tasks that add hosts in the a group is not played. 

Just adding a tag "always" to pre_tasks should fix this issue.

Mathis

**Comment by btravouillon** [comment]
Is it a role shipped with BlueBanquise? If so, which one?

**Comment by gavillom** [comment]
Sorry, my ticket is not so clear.

Playbook example given here : https://bluebanquise.com/documentation/roles/addons/diskless/readme.html#customizing-livenet-image

**Comment by btravouillon** [comment]
OK. The playbook snippet is an example, you can add any tag you want to the pre_task.
Indeed, if you want to run a given playbook with --tags and execute the pre_task, you will have to add a tag as well. This is pure Ansible.

What do you expect from us?

**Comment by gavillom** [comment]
Just adding tag: always in the example of the documentation. 
I think that would help some users.

**Comment by oxedions** [comment]
We need to add this tag, as the equipment_profile group is mandatory for this playbook to run properly. I will do the PR. 🙂

**Comment by gavillom** [comment]
Another comment on this part of documentation. This playbook is not generic : diskless image path is hard-coded.
Would propose something like this (take a look at hosts line) :

```
- name: Computes diskless playbook
  hosts: "/var/tmp/diskless/workdir/{{ img_name }}/mnt"
  connection: chroot
  vars:
    start_service: false
    j2_node_main_network: ice1-1
    image_equipment_profile: 

  pre_tasks:
    - name: Add current host to defined equipment_profile
      add_host:
        hostname: "{{ inventory_hostname }}"
        groups: "{{ image_equipment_profile }}"
      tags: always
```

and in the ansible-playbook command : add -e "img_name=<my_image_name>"

What do you think about it ?
