### ISSUE TITLE
Missing packages slurm_exporter and ha_cluster_exporter in repositories

### ISSUE THREAD

**Issue by osmocl** [bluebanquise/bluebanquise#429]
The package `slurm_exporter` and `ha_cluster_exporter` described in `roles/addons/prometheus_client/readme.rst` are missing in bluebanquise repositories: [https://bluebanquise.com/repository/releases/1.3/el8/x86_64/bluebanquise/](https://bluebanquise.com/repository/releases/1.3/el8/x86_64/bluebanquise/)

```
# cat roles/addons/prometheus_client/readme.rst
[...]

  monitoring:
    exporters:
      node_exporter:
        package: node_exporter
        service: node_exporter
        port: 9100
      ha_cluster_exporter:
        package: ha_cluster_exporter
        service: ha_cluster_exporter
        port: 9664
      slurm_exporter:
        package: slurm_exporter
        service: slurm_exporter
        scrape_interval: 5m
        scrape_timeout: 5m
        port: 9817
[...]
```
