### ISSUE TITLE
firewall role help needed

### ISSUE THREAD

**Issue by gauthierdelerce** [bluebanquise/bluebanquise#491]
Hello,
I'm using the firewall to secure the external acces to login nodes.
I followed the instructions without success and need your help to understand what I did wrong.

My goal is to allow only ssh connection through a specific interface.
I added the firewall definition to the network in the inventory : 
```
  bb:
    subnet: 158.129.164.0
    prefix: 24
    netmask: 255.255.255.0
    broadcast: 158.129.164.255
    #dhcp_unknown_range: 172.16.199.0 172.16.199.200
    gateway: 158.129.164.1
    is_in_dhcp: false
    is_in_dns: false
    firewall:
      zone: backbone
    routes4:
      - ip = 0.0.0.0/0, nh = 158.129.164.1
```

and a firewall defintion :
```
 firewall_zones:
    - zone: backbone
      masquerade: false
      services_enabled:
        - ssh
```

A zone named backbone can not be used, therefore I used the external.

After applying the role, I observed the filtering is done on the IP address, therefore the rule doesn't apply for connection which are not coming for the subnet.
```
external (active)
  target: default
  icmp-block-inversion: no
  interfaces: 
  sources: 158.129.164.0/24
  services: ssh
```

I might be better to define the rule with the interface 

I also observed that the role add rules, but doesn't ensure the state of the firewall is the expected one.
IMHO if we remove a service from the firewall definition in ansible, it should be removed on the node too.

Thanks for your help
