### ISSUE TITLE
Add DEFROUTE options in NIC role

### ISSUE THREAD

**Issue by SckyzO** [bluebanquise/bluebanquise#513]
Assume that we have four network cards, with multiple network, we have provided IP,subnet and gateway in all network card. Now system uses all cards to reach the destination.

When you put "DEFROUTE=yes" on one card then system always use card one on priority to reach every destination.

`more roles/core/nic/templates/ifcfg.j2`
```
{%if item.defroute is defined and item.defroute == true %}
DEFROUTE=yes
{% else %}
DEFROUTE=no
{% endif %}
```

Example inventory
```
[...]
    equipment_metrics:
      hosts:
        hendrixmetrics:
          bmc:
            name: hendrixmetrics-bmc
            ip4: 192.168.1.102
            mac: xx:xx:xx:xx:xx:xx:xx
            network: mn1-1
          network_interfaces:
            - interface: eno1
              ip4: 192.168.1.2
              mac: xx:xx:xx:xx:xx:xx:xx
              network: mn1-1
              defroute: true
            - interface: bond0
              type: bond
              bond_options: "mode=4 xmit_hash_policy=layer3+4 miimon=100 lacp_rate=1"
              ip4: 192.168.200.69
              network: ic1-1
            - interface: enp1s0
              type: bond-slave
              master: bond0
            - interface: enp129s0
              type: bond-slave
              master: bond0
[...]
```
