### ISSUE TITLE
hostkey_checking is global 

### ISSUE THREAD

**Issue by yhenriet** [bluebanquise/bluebanquise#537]
Hello, 
It seems that the hostkey settings is set globaly for every host
from inventory/group_vars/all/general_settings/security.yml:
```
---
security:
  ssh:
    hostkey_checking: true # enable or disable hostkey checking
```

We can add the var to the host , but the role ssh_master is not using it in this way :

From roles/core/ssh_master/templates/config.j2 : 

```
Host {{ host }}
    {% if **security.ssh.hostkey**_checking is not defined or
          security.ssh.hostkey_checking == false %}
    StrictHostKeyChecking no
    UserKnownHostsFile=/dev/null
    {% endif %}
```
So we can't only define the host check for only one host for example . 

But may be we are thinking wrong :)
