### ISSUE TITLE
Define nfs export_arguments per equipment group

### ISSUE THREAD

**Issue by gavillom** [bluebanquise/bluebanquise#598]
Hi everyone,

We're looking for a solution to define export_arguments per equipment group. Our use-case is we need no_root_squash option for some cluster administration purposes but we would prefer to clearly choose the type of nodes we allow it.

What do you think about implementing such feature into bluebanquise ?

Thanks

Mathis

**Comment by oxedions** [comment]
Dear @gavillom 

This is already implemented.

If I understand you well, you wish to specify different nfs parameters per equipment profiles ?

Solution is the following: `group_vars/equipment_X` has greater precedence over `group_vars/all`.

So you can define in `group_vars/all/general_settings/nfs.yml` some parameters, and define others in `group_vars/equipment_X/nfs.yml`. All hosts will use the one from `group_vars/all/general_settings/nfs.yml`, and memebers of *equipment_X* will use the one from `group_vars/equipment_X/nfs.yml`.

Would that be what you are looking for ? 😊

**Comment by gavillom** [comment]
@oxedions,

My functional need is to have a way to enable no_root_squash option that is part of export_arguments parameter only for few client node types (for example, I want to have root access on a mangement node to my NFS filesystems and not on compute nodes). 
So from what I understand, export_arguments (that is used by **nfs_server** role) will take care of global _nfs_ settings and not per equipment type. Am I right ?

For _mount_ parameter (used by nfs_client role), I agree that would work. But this is not what I'm looking for.

**Comment by oxedions** [comment]
Dear @gavillom 

You are right, my apologies, I did not understood your need.

Please give me few days to compute that need. If you have a nice idea between on how to format inventory for that, please do not hesitate to propose 😊 

Have a nice weekend !

**Comment by gavillom** [comment]
No problem.

I've done a small POC on my side with the following inventory definition.

```yaml
nfs:
  my_mountpoint:
    mount: /my_mountpoint
    export: /my_mountpoint
    server: nfs-server                                              
    clients_groups:                                                 
      - name: mg_managements
        export_arguments: rw,no_root_squash,async
      - mg_computes
      - mg_logins
    take_over_network: ib0                                          
    export_arguments: rw,root_squash,async
    mount_arguments: nfsvers=4.2,bg
```

This lets the ability to support current nfs inventory definition and also can provide some export_arguments for some equipment_groups. I can propose a PR if this definition suits you.

Have a nice week
