### ISSUE TITLE
nic_nmcli docs say that appending the netmask to IPv4 address is ok but breaks other roles

### ISSUE THREAD

**Issue by neilmunday** [bluebanquise/bluebanquise#616]
In the readme for the `nic_nmcli` readme it states:

```
network_interfaces:
    - interface: eth0
      ip4: 10.10.0.1/16,10.10.0.2/16
      network: ice1-1
```

If you define ip4 addresses with the subnet mask as above it breaks other roles, e.g. `hosts_file`, `dns_server` etc. as they can't handle the mask.
