### ISSUE TITLE
pxe_stack role creates incorrectly named osdeploy file for Rocky Linux

### ISSUE THREAD

**Issue by neilmunday** [bluebanquise/bluebanquise#622]
Example equipment profile definition:

```
ep_operating_system:
  distribution: rockylinux
  distribution_major_version: 8
  distribution_version: 8.4
```

When running the `pxe_stack` role this creates the following osdeploy files:

```
almalinux_8.ipxe
centos_7.ipxe
centos_8.ipxe
cloudlinux_8.ipxe
oraclelinux_8.ipxe
redhat_7.ipxe
redhat_8.ipxe
redhat_9.ipxe
rocky_8.ipxe
ubuntu_18.ipxe
ubuntu_20.ipxe
```

As a result when a node is deployed it cannot find "rockylinux_8.ipxe".
