### ISSUE TITLE
Extend supported data model to include BMC/switches and their authentication details 

### ISSUE THREAD

**Issue by ginomcevoy** [bluebanquise/bluebanquise#639]
Hello,

This is a request to extend the "inventory data model reference" (I add this link so others know what this is, https://github.com/bluebanquise/bluebanquise/blob/master/resources/data_model.md ). The extension is meant to support other equipment items different from management, login or compute nodes, for example BMCs and switches. The main elements to configure are the network and the authentication details.

## Context

There is a requirement to use BlueBanquise features to manage different BMC/switches, using varied authentication mechanisms, such as SSH, IPMI and SNMP.

However, currently the BlueBanquise data model does not directly support adding these details to BMCs. This is because BMCs are only described as an element of the node the are meant to control, and are not members of any equiment group. Bluebanquise roles that configure the interaction with BMCs, such as conman and powerman, access the network details of a BMC through its node, and then only use the authentication mechanism provided by the equipment group for which the node is a member.

This approach has the following limitations:
a) cannot define different credentials for two BMCs that correspond to the same equipment group.  
b) cannot define more than one way to access a device, for example we cannot use both SSH and IPMI on a BMC.

## Feature

The desired functionalities involve supporting the following inventory elements:

1. BMCs as hosts: The BMC would be "promoted" to an ansible host, and an ansible group can declared to be comprised of BMC hosts, each with its own network interface(s) defined exactly like other nodes. Then, we can add the "ep_host_authentication" property to each BMC For example:

```
cluster/nodes/infras.yml
mg_infra:
  children:
    equipment_mc:
      hosts:
        bmc-management1:
          network_interfaces:
            - name: bmc-management1
              ip4: 10.100.0.1
              mac: "aa:bb:cc:dd:ee:01"
              network: ice1-2
          ep_host_authentication:
            - protocol: IPMI
              user: bmcuser
              password: bmcpass
        bmc-management2:
          network_interfaces:
            - name: bmc-management2
              ip4: 10.100.0.2
              mac: "aa:bb:cc:dd:ee:02"
              network: ice1-2
          ep_host_authentication:
            - protocol: IPMI
              user: bmcuser
              password: bmcpass
...
```

Note that this would solve limitation a). We still need a way to know which BMC belongs to which node, for this we could keep the "bmc" property of each node like it is today:

```
cluster/nodes/managements.yml
mg_managements:
  children:
    equipment_typeM:
      hosts:
        management1:
          bmc:
            name: bmc-management1
...
```

2. Equipment group for devices such as BMCs or switches: 

The idea is to have the possibility of providing a default entry for ep_host_authentication at the equipment group level, this can apply to either BMCs or switches. We also have the requirement to support a list of authentication mechanisms, for example here we can manage a group of switches:

```
group_vars/equipment_type_switch/equipment_profile.yml

ep_equipment_type: switch

ep_host_authentication:
  - protocol: SNMP
    user: snmpuser
    password: snmppass
  - protocol: SSH
    user: sshuser
    password: sshpass
``` 
This would solve limitation b) above.

Note that many roles would be affected by these new inventory elements, such as: dhcp_server, advanced_dhcp_server, dns_server, advanced_dns_server, conman, powerman, hosts_file.

But, I think that if we keep ['bmc']['name'] and somehow manage to access the first network interface of the BMC via its node with some jinja magic (so that ['bmc']['ip4'], ['bmc']['network'] continue to work), then we would only to modify conman and powerman roles because of the authentication mechanisms. And, for that we could use a fallback behavior to continue using the existing ep_equipment_authentication if ep_host_authentication is not defined.
