### ISSUE TITLE
[BUG] - pxe_stack role error when generating templates for PXe boot if equipment are empty.

### ISSUE THREAD

**Issue by strus38** [bluebanquise/bluebanquise#686]
When the inventory contains such list of hosts:
```
mg_computes:
  children:
    equipment_typeC:
      hosts:
```
The pxe_stack crashes while looking at the `when:` statement in the file: `https://github.com/bluebanquise/bluebanquise/blob/master/roles/core/pxe_stack/tasks/client_os/RedHat.yml`

```
- name: "template █ Generate kickstarts {{ pxe_stack_htdocs_path }}/equipment_profiles/{item}.kickstart.cfg"
  ansible.builtin.template:
    src: "RedHat/kickstart.cfg.j2"
    dest: "{{ pxe_stack_htdocs_path }}/equipment_profiles/{{ item | replace(equipment_naming+'_','') | trim }}.kickstart.cfg"
    mode: 0644
    owner: "{{ pxe_stack_apache_user }}"
    group: "{{ pxe_stack_apache_group }}"
  with_items: "{{ j2_equipment_groups_list }}"
  when:
    - hostvars[groups[item][0]]['ep_equipment_type'] == 'server'
    - (hostvars[groups[item][0]]['ep_operating_system']['distribution']|lower) in ['redhat','centos','rockylinux','cloudlinux','oraclelinux','almalinux']
  tags:
    - template
```

The idea would be to better handle the `when:` statements to catch those kind of inventories.
Also, taking into account the fact that ep_equipment_type could be 'none' or non-existing would be better.

Of course this would have to be solved everywhere :-)
