### ISSUE TITLE
[BUG] ssh_remote_keys only add keys to root account

### ISSUE THREAD

**Issue by wlln** [bluebanquise/bluebanquise#715]
BlueBanquise allows being run as a privileged user. 
Some roles now uses the `ansible_env.SUDO_USER` variable to check which user should be impacted with the role.

ssh_remote_keys isn't (yet).

## Possible Fix

in `tasks/main.yml`, replace `user: root` with:
```yaml
- name: authorized_key █ Add authorized key
  ansible.posix.authorized_key:
    user: "{% if ansible_env.SUDO_USER is defined %}/home/{{ ansible_env.SUDO_USER }}{% else %}/root{% endif %}/.ssh"
    key: "{{ item }}"
    exclusive: no
    state: present
  with_items: "{{ authentication_ssh_keys }}"
```
