### ISSUE TITLE
[BUG] dns_server role: overlapping reverse zone files for small subnets

### ISSUE THREAD

**Issue by sla31** [bluebanquise/bluebanquise#724]
Hi,

When 2 networks are defined in the inventory with a small prefix (like /30 for instance), the `dns_server` role uses the same file name for both `named` reverse zone files.

Here's an inventory excerpt:
```yaml
  heartbeat:
    subnet: 172.26.0.4
    prefix: 30
    netmask: 255.255.255.252
    broadcast: 172.26.0.7
    is_in_dns: true
  direct-cisco01:
    subnet: 172.26.0.0
    prefix: 30
    netmask: 255.255.255.252
    broadcast: 172.25.255.255
    is_in_dns: true
  direct-cisco02:
    subnet: 172.26.0.8
    prefix: 30
    netmask: 255.255.255.252
    broadcast: 172.26.0.11
    is_in_dns: true
```

So we have 3 small subnets (/30 → netmask=255.255.255.252) which want to be in the DNS.

Here's what the execution of the `dns_server` gives:
```
TASK [dns_server : template █ Generate Reverse zone file on Master DNS {{ dns_server_named_dir }}/{{ item }}.rr.zone] **********************
Saturday 04 June 2022  15:16:25 +0200 (0:00:00.170)       0:00:06.843 ********* 
--- before: /etc/named/172.26.0.rr.zone
+++ after: /home/pstaff/.ansible/tmp/ansible-local-11099301cwgzzn0/tmpjx6t1yzd/reverse.j2
@@ -7,4 +7,5 @@
 @ IN NS head02.my.localdomain.

-9 IN PTR head02-direct-cisco02.my.localdomain.
+5 IN PTR head01-heartbeat.my.localdomain.
+6 IN PTR head02-heartbeat.my.localdomain.

changed: [head02] => (item=172.26.0)

TASK [dns_server : template █ Generate Reverse zone file on Master DNS {{ dns_server_named_dir }}/{{ item }}.rr.zone] **********************
Saturday 04 June 2022  15:16:28 +0200 (0:00:00.197)       0:00:09.798 ********* 
--- before: /etc/named/172.26.0.rr.zone
+++ after: /home/pstaff/.ansible/tmp/ansible-local-11099301cwgzzn0/tmpp3sb6f2s/reverse.j2
@@ -7,5 +7,4 @@
 @ IN NS head02.my.localdomain.
 
-5 IN PTR head01-heartbeat.my.localdomain.
-6 IN PTR head02-heartbeat.my.localdomain.
+1 IN PTR head01-direct-cisco01.my.localdomain.

changed: [head02] => (item=172.26.0)

TASK [dns_server : template █ Generate Reverse zone file on Master DNS {{ dns_server_named_dir }}/{{ item }}.rr.zone] **********************
Saturday 04 June 2022  15:16:29 +0200 (0:00:00.232)       0:00:11.175 ********* 
--- before: /etc/named/172.26.0.rr.zone
+++ after: /home/pstaff/.ansible/tmp/ansible-local-11099301cwgzzn0/tmpgtjvmyzu/reverse.j2
@@ -7,4 +7,4 @@
 @ IN NS head02.my.localdomain.

-1 IN PTR head01-direct-cisco01.my.localdomain.
+9 IN PTR head02-direct-cisco02.my.localdomain.

changed: [head02] => (item=172.26.0)
```

The same reverse zone file `172.26.0.rr.zone` gets overwritten 3 times in a row.

I guess it might be safer to use the **complete base IP address** of the subnet to name the zone file...

Thanks!
