### ISSUE TITLE
[BUG] Nic Role does not Update interface type chages

### ISSUE THREAD

**Issue by santos-lucas** [bluebanquise/bluebanquise#739]
I have This configuration on my node:
```
[root@mds02 network-scripts]# cat ifcfg-ib0 
TYPE=Ethernet
PROXY_METHOD=none
BROWSER_ONLY=no
BOOTPROTO=none
IPADDR=10.27.165.249
PREFIX=22
DEFROUTE=yes
IPV4_FAILURE_FATAL=no
IPV6INIT=yes
IPV6_AUTOCONF=yes
IPV6_DEFROUTE=yes
IPV6_FAILURE_FATAL=no
IPV6_ADDR_GEN_MODE=stable-privacy
NAME=ib0
```
So I changed the inventory configuration for:
```yaml
  gr12fs01mds02:
          bmc:
            name: gr12fs01mds02-ipmi
            ip4: 172.20.100.4
            mac: 3c:ec:ef:2e:20:46
            network: ice1-1
          network_interfaces:
            - interface: eno1
              ip4: 172.20.0.4
              mac: 3c:ec:ef:30:16:08
            - interface: ib0
              ip4: 10.27.165.249
              type: infiniband
              network: ic1
```

And after running the NIC role nothing is changed, only if I remove the file and run an `nmcli con reload`, because in this case the previous config will really not exist
