### ISSUE TITLE
[BUG] nic role: nic_force_nic_restart=true not working okay

### ISSUE THREAD

**Issue by santos-lucas** [bluebanquise/bluebanquise#752]
nic_force_nic_restart=true seems to not be working okay with bonding configuration, access is being lost.

As can be seen in the following:
```
TASK [nic : shell █ Force apply nic settings] *************************************************************************
Thursday 27 October 2022  00:18:33 -0300 (0:00:00.039)       0:00:42.012 ****** 
[WARNING]: The loop variable 'item' is already in use. You should set the `loop_var` value in the `loop_control`
option for the task to something else to avoid variable collisions and unexpected behavior.
changed: [g002] => (item={'conn_name': 'bond0', 'state': 'present', 'Connection': 'Connection bond0 of Type bond is being added', 'changed': True, 'stdout': 'Connection successfully activated (master waiting for slaves) (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/675)\n', 'invocation': {'module_args': {'conn_name': 'bond0', 'ip4': ['172.20.0.7/16'], 'dns4': ['172.20.0.1'], 'type': 'bond', 'state': 'present', 'mode': '802.3ad', 'ignore_unsupported_suboptions': False, 'autoconnect': True, 'gw4_ignore_auto': False, 'never_default4': False, 'dns4_ignore_auto': False, 'may_fail4': True, 'gw6_ignore_auto': False, 'dns6_ignore_auto': False, 'stp': True, 'priority': 128, 'slavepriority': 32, 'forwarddelay': 15, 'hellotime': 2, 'maxage': 20, 'ageingtime': 300, 'path_cost': 100, 'runner': 'roundrobin', 'master': None, 'ifname': None, 'gw4': None, 'routes4': None, 'routes4_extended': None, 'route_metric4': None, 'routing_rules4': None, 'dns4_search': None, 'method4': None, 'dhcp_client_id': None, 'ip6': None, 'gw6': None, 'dns6': None, 'dns6_search': None, 'routes6': None, 'routes6_extended': None, 'route_metric6': None, 'method6': None, 'ip_privacy6': None, 'addr_gen_mode6': None, 'miimon': None, 'downdelay': None, 'updelay': None, 'arp_interval': None, 'arp_ip_target': None, 'primary': None, 'mtu': None, 'mac': None, 'zone': None, 'hairpin': None, 'runner_hwaddr_policy': None, 'vlanid': None, 'vlandev': None, 'flags': None, 'ingress': None, 'egress': None, 'vxlan_id': None, 'vxlan_local': None, 'vxlan_remote': None, 'ip_tunnel_dev': None, 'ip_tunnel_local': None, 'ip_tunnel_remote': None, 'ip_tunnel_input_key': None, 'ip_tunnel_output_key': None, 'ssid': None, 'wifi': None, 'wifi_sec': None, 'gsm': None, 'wireguard': None, 'vpn': None}}, 'stdout_lines': ['Connection successfully activated (master waiting for slaves) (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/675)'], 'failed': False, 'item': {'interface': 'bond0', 'type': 'bond', 'mode': '802.3ad', 'ip4': '172.20.0.7', 'mac': '3c:ec:ef:05:1c:dc', 'network': 'ice1-1'}, 'ansible_loop_var': 'item'})
failed: [g002] (item={'conn_name': 'eno1', 'state': 'present', 'Exists': 'Connections do exist so we are modifying them', 'changed': True, 'invocation': {'module_args': {'conn_name': 'eno1', 'type': 'bond-slave', 'state': 'present', 'master': 'bond0', 'ignore_unsupported_suboptions': False, 'autoconnect': True, 'gw4_ignore_auto': False, 'never_default4': False, 'dns4_ignore_auto': False, 'may_fail4': True, 'gw6_ignore_auto': False, 'dns6_ignore_auto': False, 'mode': 'balance-rr', 'stp': True, 'priority': 128, 'slavepriority': 32, 'forwarddelay': 15, 'hellotime': 2, 'maxage': 20, 'ageingtime': 300, 'path_cost': 100, 'runner': 'roundrobin', 'ifname': None, 'ip4': None, 'gw4': None, 'routes4': None, 'routes4_extended': None, 'route_metric4': None, 'routing_rules4': None, 'dns4': None, 'dns4_search': None, 'method4': None, 'dhcp_client_id': None, 'ip6': None, 'gw6': None, 'dns6': None, 'dns6_search': None, 'routes6': None, 'routes6_extended': None, 'route_metric6': None, 'method6': None, 'ip_privacy6': None, 'addr_gen_mode6': None, 'miimon': None, 'downdelay': None, 'updelay': None, 'arp_interval': None, 'arp_ip_target': None, 'primary': None, 'mtu': None, 'mac': None, 'zone': None, 'hairpin': None, 'runner_hwaddr_policy': None, 'vlanid': None, 'vlandev': None, 'flags': None, 'ingress': None, 'egress': None, 'vxlan_id': None, 'vxlan_local': None, 'vxlan_remote': None, 'ip_tunnel_dev': None, 'ip_tunnel_local': None, 'ip_tunnel_remote': None, 'ip_tunnel_input_key': None, 'ip_tunnel_output_key': None, 'ssid': None, 'wifi': None, 'wifi_sec': None, 'gsm': None, 'wireguard': None, 'vpn': None}}, 'failed': False, 'item': {'interface': 'eno1', 'type': 'bond-slave', 'master': 'bond0'}, 'ansible_loop_var': 'item'}) => 
  ansible_loop_var: item
  item:
    Exists: Connections do exist so we are modifying them
    ansible_loop_var: item
    changed: true
    conn_name: eno1
    failed: false
    invocation:
      module_args:
        addr_gen_mode6: null
        ageingtime: 300
        arp_interval: null
        arp_ip_target: null
        autoconnect: true
        conn_name: eno1
        dhcp_client_id: null
        dns4: null
        dns4_ignore_auto: false
        dns4_search: null
        dns6: null
        dns6_ignore_auto: false
        dns6_search: null
        downdelay: null
        egress: null
        flags: null
        forwarddelay: 15
        gsm: null
        gw4: null
        gw4_ignore_auto: false
        gw6: null
        gw6_ignore_auto: false
        hairpin: null
        hellotime: 2
        ifname: null
        ignore_unsupported_suboptions: false
        ingress: null
        ip4: null
        ip6: null
        ip_privacy6: null
        ip_tunnel_dev: null
        ip_tunnel_input_key: null
        ip_tunnel_local: null
        ip_tunnel_output_key: null
        ip_tunnel_remote: null
        mac: null
        master: bond0
        maxage: 20
        may_fail4: true
        method4: null
        method6: null
        miimon: null
        mode: balance-rr
        mtu: null
        never_default4: false
        path_cost: 100
        primary: null
        priority: 128
        route_metric4: null
        route_metric6: null
        routes4: null
        routes4_extended: null
        routes6: null
        routes6_extended: null
        routing_rules4: null
        runner: roundrobin
        runner_hwaddr_policy: null
        slavepriority: 32
        ssid: null
        state: present
        stp: true
        type: bond-slave
        updelay: null
        vlandev: null
        vlanid: null
        vpn: null
        vxlan_id: null
        vxlan_local: null
        vxlan_remote: null
        wifi: null
        wifi_sec: null
        wireguard: null
        zone: null
    item:
      interface: eno1
      master: bond0
      type: bond-slave
    state: present
  msg: 'Failed to connect to the host via ssh: ssh: connect to host g002-ice1-1 port 22: Connection timed out'
  unreachable: true
```

That is the node configuration:
```yaml
mg_computes:
  children:
    equipment_typeG:
      hosts:
        g001:
          bmc:
            name: bg001
            ip4: 172.20.100.8
            mac: 3c:ec:ef:2e:d2:4b
            network: ice1-1
          network_interfaces:
            - interface: bond0
              type: bond
              mode: 802.3ad
              ip4: 172.20.0.8
              mac: 3c:ec:ef:05:30:b6
              network: ice1-1
            - interface: eno1
              type: bond-slave
              master: bond0
            - interface: eno2
              type: bond-slave
              master: bond0

            - interface: bond1
              mode: 802.3ad
              ip4: 10.20.5.1
              network: interconnect-1
              type: bond
            - interface: ens8f0
              type: bond-slave
              master: bond1
            - interface: ens8f1
              type: bond-slave
              master: bond1
        g002:
          bmc:
            name: bg002
            ip4: 172.20.100.7
            mac: 3c:ec:ef:2e:a7:dc
            network: ice1-1
          network_interfaces:
            - interface: bond0
              type: bond
              mode: 802.3ad
              ip4: 172.20.0.7
              mac: 3c:ec:ef:05:1c:dc
              network: ice1-1
            - interface: eno1
              type: bond-slave
              master: bond0
            - interface: eno2
              type: bond-slave
              master: bond0

            - interface: bond1
              mode: 802.3ad
              ip4: 10.20.5.2
              network: interconnect-1
              type: bond
            - interface: ens8f0
              type: bond-slave
              master: bond1
            - interface: ens8f1
              type: bond-slave
              master: bond1

```
