### ISSUE TITLE
[BUG] Disabling network interfaces leads to failure in firewall role

### ISSUE THREAD

**Issue by GaelBil** [bluebanquise/bluebanquise#814]
Disabling network interfaces leads to failure in firewall role

## Context

If you want to disable network interfaces by using the following variables in you inventory, it leads to a failure in the firewall role
```
            - interface: eno2
              method4: disabled
              method6: disabled
```

## Process

To reproduce this issue, use the previous variables for an interface without adding other information (IP adresse, gateway...)

## Expected result

The expected result is th firewall role should not take care of this interface which does not have any network information.

## Current result

The firewall role complain missing network information.

## Possible Fix

```
cat firewall/tasks/RedHat/main.yml

- name: fail ░ Check presence of required parameters
  fail:
    msg: "Bailing out.
  This role requires networks[{{ item['network'] }}]['firewall']['zone']"
  when: item['network'] is defined and networks[item['network']]['firewall']['zone'] is not defined
  loop: "{{ network_interfaces }}"
  loop_control:
    label: "{{ item['interface'] }}"
  tags:
    - internal

- name: "firewalld █ Ensure firewall zones exist"
  firewalld:
    zone: "{{ networks[item]['firewall']['zone'] }}"
    permanent: yes
    state: present
  when: networks[item]['firewall']['zone'] is defined
  loop: "{{ (network_interfaces | selectattr('network','defined') | map(attribute='network') | list) }}"
  notify: service █ Restart firewall services

- name: meta █ Run handler tasks to restart firewall services
  meta: flush_handlers

- name: "firewalld █ Configure firewall zones"
  firewalld:
    zone: "{{ networks[item]['firewall']['zone'] }}"
    source: "{{ networks[item]['subnet'] }}/{{ networks[item]['prefix'] }}"
    immediate: yes
    permanent: yes
    state: enabled
  when: networks[item]['firewall']['zone'] is defined
  loop: "{{ (network_interfaces | selectattr('network','defined') | map(attribute='network') | list) }}"
  loop_control:
    label: "Add source '{{ networks[item]['subnet'] }}/{{ networks[item]['prefix'] }}'
            to zone '{{ networks[item]['firewall']['zone'] }}'"

[...]
```
