### ISSUE TITLE
BB-15 - [FEATURE REQUEST] define a global services ip with specific ip for a service

### ISSUE THREAD

**Issue by toto-xoxo** [bluebanquise/bluebanquise#858]
It may be useful to define a global IP for all services and only a different IP for one service. Currently, if a global IP is defined, the rest is ignored. This could make it possible not to define all the services one by one when the IP is different only for one or two services.

## Context

network config :

```
networks:
  net-admin1:
    subnet: 10.10.0.0
    prefix: 16
    services_ip: 10.10.0.1
    services:
      repositories:
        - ip4: 172.XX.XXX.X
          hostname: othernode
  mgmt1:
    subnet: 10.20.0.0
    prefix: 16
```

## Feature

Take into account the `ip4` of the service if it is defined even if there is a `services_ip`.
