### ISSUE TITLE
BB-19 - [BUG] collections/hardware/interconnect role variable name missmatch

### ISSUE THREAD

**Issue by corentin-g** [bluebanquise/bluebanquise#869]
Dear team

## Context
We are trying to run the role bluebanquise.hardware.interconnect 
Some variables that clearly have the same role have several different names:

### Role default name (and documentation)
default variable name in collections/hardware/roles/interconnect/defaults/main.yml:

```yaml
interconnect_ofed_memlock_soft: 'unlimited'
interconnect_ofed_memlock_hard: 'unlimited'
interconnect_ofed_client: false
interconnect_ofed_subnet_manager: false
```

### Role task main name
Variable name used in collections/hardware/roles/interconnect/tasks/ofed/RedHat/main.yml: 
- ofed_client
- ofed_subnet_manager

```yaml
(...)
- name: include_tasks <|> Setup infiniband client
  ansible.builtin.include_tasks: "client.yml"
  when: ofed_client
  tags:
    - internal

- name: include_tasks <|> Setup infiniband subnet manager
  ansible.builtin.include_tasks: "subnet_manager.yml"
  when: ofed_subnet_manager
  tags:
    - internal
(...)
```

Thanks for your help !
