### ISSUE TITLE
BB-22 - [BUG] Prometheus - prometheus.yml SNMP modules missing

### ISSUE THREAD

**Issue by michaelhoehl** [bluebanquise/bluebanquise#871]
Dear Team,

## Context

the template for the prometheus.yml has already an section for the SNMP_EXPORTER, but the metrics part section with the module is excluded. I don't find any reason for that and in the most installation we have multiple devices where we collect SNMP metrics with our defined modules

## Expected result

SNMP exporter should use the defined modules to collect valid metrics.

## Possible Fix

I changed in the prometheus.yml.j2 template file the SNMP_EXPORTER section to the following:

```
# SNMP_EXPORTER
{% for equipment in  prometheus_snmp_scrape_equipment_profiles %}
  - job_name: 'snmp_{{equipment.name}}'
    scrape_interval: {{ equipment.scrape_interval | default('') }}
    scrape_timeout: {{ equipment.scrape_timeout | default('') }}
    static_configs:
     - targets:
    {% for node in groups[equipment.name] %}
       - {{ node }}
    {% endfor %}

    metrics_path: /snmp
    params:
      module: [{{ equipment.snmp_module }}]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: {{ prometheus_server_snmp_exporter_host }}:9116
{% endfor %}
```

That give the option to define the  needed SNMP module in the inventory file like this:

```
prometheus_snmp_scrape_equipment_profiles:
  - name: eq_pdu
    snmp_module: pdu
  - name: eq_cumulus
    snmp_module: swl
  - name: eq_wcd
    snmp_module: wcd


```

## Additional data

In my installation this worked fine. Would be good to include this per default if there is no good reason to not do it.
