### ISSUE TITLE
[BUG] nfs export use <hostname>-<network name> instead of just <hostname>

### ISSUE THREAD

**Issue by sgaosdgr** [bluebanquise/bluebanquise#887]
When set "hosts_file_enable_extended_names: false" and  "dns_server_enable_extended_names: false", nfs role still use extended name for NFS share.   It should use the default <hostname>.cluster.local

## Context

When set "hosts_file_enable_extended_names: false" and  "dns_server_enable_extended_names: false", nfs role still use extended name for NFS share.  As a result, mounting an NFS share failed due to not able to resolve <hostname>-<network name>.  

Error message:
```
TASK [bluebanquise.file_systems.nfs : mount <|> Mount exported NFS into directories] ******************************************************************************************
Wednesday 14 February 2024  12:48:11 -0800 (0:00:00.033)       0:00:28.446 **** 
skipping: [mgt1] => (item=[{'export': '/export/apps', 'server': 'mgt1', 'mount': '/share/apps', 'network': 'net-1', 'export_options': 'ro,no_root_squash,async', 'export_arguments': 'ro,no_root_squash,async', 'mount_options': 'ro,nfsvers=4.2,hard,nosuid,nodev,noatime,nodiratime,retrans=3', 'mount_arguments': 'ro,nfsvers=4.2,hard,nosuid,nodev,noatime,nodiratime,retrans=3'}, 'fn_compute']) 
skipping: [mgt1] => (item=[{'export': '/export/apps', 'server': 'mgt1', 'mount': '/share/apps', 'network': 'net-1', 'export_options': 'ro,no_root_squash,async', 'export_arguments': 'ro,no_root_squash,async', 'mount_options': 'ro,nfsvers=4.2,hard,nosuid,nodev,noatime,nodiratime,retrans=3', 'mount_arguments': 'ro,nfsvers=4.2,hard,nosuid,nodev,noatime,nodiratime,retrans=3'}, 'fn_login']) 
failed: [mgt1] (item=[{'export': '/export/apps', 'server': 'mgt1', 'mount': '/share/apps', 'network': 'net-1', 'export_options': 'ro,no_root_squash,async', 'export_arguments': 'ro,no_root_squash,async', 'mount_options': 'ro,nfsvers=4.2,hard,nosuid,nodev,noatime,nodiratime,retrans=3', 'mount_arguments': 'ro,nfsvers=4.2,hard,nosuid,nodev,noatime,nodiratime,retrans=3'}, 'fn_management']) => changed=false 
  ansible_loop_var: item
  item:
  - export: /export/apps
    export_arguments: ro,no_root_squash,async
    export_options: ro,no_root_squash,async
    mount: /share/apps
    mount_arguments: ro,nfsvers=4.2,hard,nosuid,nodev,noatime,nodiratime,retrans=3
    mount_options: ro,nfsvers=4.2,hard,nosuid,nodev,noatime,nodiratime,retrans=3
    network: net-1
    server: mgt1
  - fn_management
  msg: |-
    Error mounting /share/apps: mount.nfs: Failed to resolve server mgt1-net-1: Name or service not known
````

## Process

1. Set disable extended names:
```
 hosts_file_enable_extended_names: false
 dns_server_enable_extended_names: false
```

2. Run `hosts_file` and `dns_server` 
3. Run nfs role

## Expected result

Should mount <hostname>:/export/share

## Current result

Actually it mounts <hostname>-<network name>:/export/share.   <hostname>-<network name> record no longer exists

## Additional data

An example of nfs export:
```
fs_shares:
  - export: /export/apps                        # What path server should export
    server: mgt1                          # The server that export this storage space
    mount: /share/apps                          # Which path clients should mount this NFS
    clients_groups:                             # Can be an equipment group, or a main group (mg), or any other ansible group
      - fn_compute
      - fn_login
      - fn_management
    network: net-1                              # Network used to share this storage space
    export_options: ro,no_root_squash,async     # Options for the server (export)
    export_arguments: ro,no_root_squash,async   # Arguments for the server (export)
    mount_options: ro,nfsvers=4.2,hard,nosuid,nodev,noatime,nodiratime,retrans=3      # Arguments for the client (mount)
    mount_arguments: ro,nfsvers=4.2,hard,nosuid,nodev,noatime,nodiratime,retrans=3       # Arguments for the client (mount)
```
