### ISSUE TITLE
BB-31 - [FEATURE REQUEST] Allow different sudoers files

### ISSUE THREAD

**Issue by sgaosdgr** [bluebanquise/bluebanquise#900]
Sudoers role updates /etc/sudoers file for managing sudo permissions for user or group by default. At times, people may want to create/manage a separate sudoers files for some users or groups and put the sudoers files in /etc/sudoers.d directory.  Modifying /etc/sudoers file may not be the best choice. 

## Context

We can improve sudoers role to include the option to add sudo permissions in a specified file in /etc/sudoers.d.

## Feature

Improvement to collections/infrastructure/roles/sudoers/tasks/main.yml:

```
- name: lineinfile <|> Add sudoers users and groups
  ansible.builtin.lineinfile:
    dest: "{{ item.file_name | default('/etc/sudoers') }}"
    state: present
    create: true
    owner: root
    group: root
    mode: '0600'
    regexp: "^{{ item.name }}"
    line: "{{ item.name }} {{ item.privilege }}"
    validate: 'visudo -cf %s'
  loop: "{{ sudoers }}"
  when: sudoers is defined and sudoers
```

The sudoers variable example:
```
sudoers:
  # Set 'manu' user as sudoer with passwordless rights
  - name: manu
    file_name: "/etc/sudoers.d/mau"
    privilege: ALL=(ALL) NOPASSWD:ALL
  # Set 'techs' group users as sudier with passwordless rights
  - name: "%techs"
    file_name: "/etc/sudoers.d/techs"
    privilege: ALL=(ALL) NOPASSWD:ALL
  - name: greenwood
    privilege: ALL=(ALL) NOPASSWD:ALL
      
## Additional data

The update continues to support adding user/group to /etc/sudoers while provides an option for creating specified sudoers files for certain users and groups.
