### ISSUE TITLE
BB-35 - [FEATURE REQUEST] copy job_submit.lua file if provided to slurm controller

### ISSUE THREAD

**Issue by vedmonds** [bluebanquise/bluebanquise#934]
Be able to deploy a custom, locally provided `job_submit.lua` file for slurm controller, which also needs to be configured in `slurm.conf`

## Context

Since the `job_submit.lua` script can be heavily customized, it doesn't make sense to try to provide  it's own template within bluebanquise collection, but the file does need to be deployed within bluebanquise slurm role. 

Recommend using `ansible.builtin.template` rather than `copy` on the off chance users are templating within their script. 

## Feature

In `collections/hpc/roles/slurm/tasks/controller.yml`
```
- name: Copy job_submit.lua file if indicated
  when: slurm_job_submit_lua_file
  ansible.builtin.template:
    src: "{{ slurm_job_submit_lua_file }}"
    dest: /etc/slurm/job_submit.lua
    owner: "{{ slurm_user_uid }}"
    group: "{{ slurm_user_gid }}"
    mode: "0444"

- name: Check JobSubmitPlugins contains lua for slurm.conf if intending to use the job_submit.lua file
  when: slurm_job_submit_lua_file
  ansible.builtin.assert:
    that: slurm_job_submit_plugins is search("lua")
```

In `collections/hpc/roles/slurm/templates/slurm.conf.j2`
```
{% if slurm_job_submit_plugins is defined and slurm_job_submit_plugins is not none %}
JobSubmitPlugins=slurm_job_submit_plugins
{% endif %}
```
