### ISSUE TITLE
BB-36 - [BUG] Need handler for scontrol reconfigure after updates to slurm.conf

### ISSUE THREAD

**Issue by vedmonds** [bluebanquise/bluebanquise#941]
When slurm.conf is updated, the slurm controller needs to issue `scontrol reconfigure`

## Context

When `scontrol reconfigure` is issued it:
1. verifies the new slurm.conf is valid
2. alerts compute nodes that there is a new version of slurm.conf (critical for when running in configless mode)

## Process

1. Update slurm.conf to include new hosts
2. Install slurmd on computes in configless mode
3. `systemctl status slurmd` on new computes will fail

## Expected result

Expect slurmd service to be running properly on new computes

## Current result

```
    Unable to start service slurmd: Job for slurmd.service failed because the control process exited with error code.
    See "systemctl status slurmd.service" and "journalctl -xeu slurmd.service" for details.
```

## Possible Fix

`collections/hpc/roles/slurm/tasks/controller.yml`
```
- name: "template <|> Generate configuration files in {{ slurm_home_path }}"
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ slurm_home_path }}/{{ item }}"
    owner: slurm
    group: slurm
    mode: 0644
  tags:
    - template
  loop:
    - slurm.conf
    - cgroup.conf
  notify: Run scontrol reconfigure
```

`collections/hpc/roles/slurm/handlers/main.yml`
```
- name: Run scontrol reconfigure
  ansible.builtin.command:
    cmd: scontrol reconfigure
  changed_when: true
```
## Additional data

[If relevant, include a screenshot, links, etc.]
