### ISSUE TITLE
[BUG] PXE Boot Fails at Kernel Loading Stage with BlueBanquise Diskless Setup on Rocky Linux

### ISSUE THREAD

**Issue by allancarlosvr** [bluebanquise/bluebanquise#994]
## Description

After setting up a PXE boot environment with BlueBanquise, I am encountering multiple issues with the PXE client failing to load the kernel (vmlinuz) over HTTP. Additionally, the nodes_parameters.yml file does not get generated automatically during the initial configuration process, which might indicate a configuration or template issue.

## Context

I am using BlueBanquise to configure and deploy a diskless PXE boot environment for a node (c001). The environment includes Rocky Linux 9.3 as the base image. The PXE server and NFS are configured on the management node (management2), and the client node (c001) is expected to boot via PXE.

## Process

Ran the following playbook to set up the PXE stack:

`ansible-playbook playbooks/management.yml -b -i inventory --limit management2 --tags pxe_stack
`
Observed that **/etc/bluebanquise/bootset/nodes_parameters.yml** was empty.

Manually updated /etc/bluebanquise/bootset/nodes_parameters.yml with the following content:

```
---
#### Blue Banquise file ####
## Ansible managed file, do not edit

nodes_parameters:
  c001:
    network: net-admin
    ip: 10.76.0.20
    mac: 08:00:27:4a:78:e8
    groups:
      - os_rockylinux_9
      - hw_virtualbox
    equipment_profile: rockylinux_default
```
Ran the command:

`sudo bluebanquise-bootset -b diskless -i rockylinux_default -n c001
`

**Result: Warning message**

```
[INFO] Loading /etc/bluebanquise/bootset/nodes_parameters.yml
[INFO] Loading /etc/bluebanquise/bootset/pxe_parameters.yml
[INFO] Checking if node c001 exist...
[WARNING] Node c001 does not exist. Skipping.
```
Attempted to boot c001 via PXE. The PXE client stopped with the error while loading vmlinuz (kernel) over HTTP. A screenshot of the error is attached below:

Screenshot:
<img width="643" alt="Screenshot 2024-12-09 at 23 28 40" src="https://github.com/user-attachments/assets/892185db-1d0d-4572-b9c2-0dc953a67509">

Verified that boot.ipxe is correctly set up with the following content:

```
#!ipxe
echo |
echo | Entering diskless/images/rockylinux_default/boot.ipxe
echo |
set image-kernel vmlinuz-5.14.0-362.18.1.el9_3.0.1.x86_64
set image-initramfs initramfs-5.14.0-362.18.1.el9_3.0.1.x86_64.img
echo | Now starting nfs image boot.
echo |
kernel http://${next-server}/pxe/diskless/rockylinux_default/${image-kernel} initrd=${image-initramfs} selinux=0 text=1 root=nfs:${next-server}:/nfs/diskless/rockylinux_default,vers=4.2,rw rw rd.net.timeout.carrier=30 rd.net.timeout.ifup=60 rd.net.dhcp.retry=4
initrd http://${next-server}/pxe/diskless/rockylinux_default/${image-initramfs}
boot
```

## Expected result

The PXE client (c001) should successfully fetch the kernel (vmlinuz) and initramfs over HTTP and boot into the NFS-mounted diskless image.

## Current result

The PXE boot process halts while loading the kernel (vmlinuz) over HTTP.

Manually checking the HTTP and NFS services confirms they are running and accessible:

showmount -e on the PXE server shows the correct export.

Apache logs confirm vmlinuz is being served:

`10.76.0.20 - - [10/Dec/2024:01:50:02 +0000] "GET /pxe/diskless/rockylinux_default/vmlinuz-5.14.0-362.18.1.el9_3.0.1.x86_64 HTTP/1.1" 200 13382184 "-" "iPXE/1.0.0+"`

## Possible Fix

Verify why nodes_parameters.yml was not generated automatically by ansible-playbook.
Investigate the possibility of a network issue causing intermittent connectivity during the PXE boot process. This could include:
DHCP lease expiration.
Incorrect routing during the PXE boot process.
Ensure that the PXE client has all necessary drivers for NFS and HTTP.

## Additional data

Server Logs:

Apache Logs (access_log):

```
10.76.0.20 - - [10/Dec/2024:01:50:02 +0000] "GET /pxe/diskless/rockylinux_default/vmlinuz-5.14.0-362.18.1.el9_3.0.1.x86_64 HTTP/1.1" 200 13382184 "-" "iPXE/1.0.0+"

```

Apache Logs (error_log):

`AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message`

NFS Configuration:

```
showmount -e
Export list for management2:
/nfs/diskless/rockylinux_default 10.76.0.0/24
```

**Comment by oxedions** [comment]
Dear @allancarlosvr 

Thank you very much for this feedback. It is highly possible I broke the PXE stack recently, I made an intrusive change.

I will debug that this week. Can you confirm me you wish to use diskless and not diskful ? To help me focus on the target.
Also, if possible, would you accept to send me a copy of your inventory to oxedions@gmail.com so I can check it ? Please note that this is just a proposal, if this inventory contains sensitive information, do not share it with me :blush:

**Comment by allancarlosvr** [comment]
Hello @oxedions, thank you by your support offer

But, I fixed my issues, I used diskfull option, and I document my POC testing using Vagrant + VirtualBox

I'm sharing here my README.md 

# BlueBanquise Cluster POC

This repository provides the steps and resources necessary to set up and manage a cluster environment using [BlueBanquise](https://bluebanquise.com) on Rocky Linux 9.5. The project uses **Vagrant** to provision a management node and **VirtualBox** for PXE bootable compute nodes.

---

## Table of Contents

1. [Introduction](#introduction)
2. [Setup Overview](#setup-overview)
3. [Prerequisites](#prerequisites)
4. [Installation](#installation)
    - [Management Node Setup](#management-node-setup)
    - [Compute Node Setup](#compute-node-setup)
5. [Configuration](#configuration)
    - [Inventory Configuration](#inventory-configuration)
    - [Management Node Configuration](#management-node-setup)
       - [Install vital Dependencies](#install-vital-dependencies)
       - [Management Deployments](#management-deployment)
       - [Others Required dependecies](#others-required-dependencies) 
    - [PXE Stack](#pxe-stack)
       - [Diskfull OS images location](#diskfull-os-images-location)
    - [Apply management2 configuration](#apply-management2-configuration)
    - [Bluebanquise-bootset usage](#bluebanquise-bootset-usage)
6. [Deploy C001 Node](#deploy-c001-node)
7. [References](#references)

---

## 1. Introduction

This Proof of Concept (POC) demonstrates the deployment of a basic cluster using BlueBanquise. It focuses on setting up a management node, configuring PXE boot for compute nodes, and managing the cluster using Ansible roles provided by BlueBanquise.

<div style="width:800px;">
  <img src="images/chart_bluebanquise.png" alt="POC BlueBanquise chart">
</div>

---

## 2. Setup Overview

The cluster setup includes:
- A management node provisioned with **Vagrant** and **VirtualBox**.
- PXE-bootable compute nodes with network settings configured via **BlueBanquise**.

---

## 3. Prerequisites

Before starting, ensure the following are installed on your host system:
- [VirtualBox](https://www.virtualbox.org/)
- [Vagrant](https://www.vagrantup.com/)
- SSH client (for key generation and testing)
- [Python 3.9 or higher and Ansible](https://bluebanquise.com/documentation/configure_bluebanquise.html#install-ansible)

---

## 4. Installation

### Management Node Setup

1. **Provision the management node:**
   - Clone the repository:
     ```bash
     git clone <repository-url>
     cd cluster_bluebanquise_poc_B
     ```
   - Start the Vagrant instance:
     ```bash
     vagrant up
     ```
   - If errors occur during provisioning, refer to the [Troubleshooting](#troubleshooting) section.

2. **Dependencies Installation:**
   - Update the system:
     ```bash
     sudo dnf update -y
     ```
   - Install required packages:
     ```bash
     sudo dnf install -y gcc make perl kernel-devel kernel-headers epel-release
     ```

3. **Ansible Installation:**
   - Activate the Python virtual environment:
     ```bash
     source /root/ansible_venv/bin/activate
     ```
   - Install Ansible:
     ```bash
     pip install ansible
     ```

---

### Compute Node Setup

1. **Create the Virtual Machine:**
   - Use VirtualBox to create a new VM with the following settings:
     - **Name:** `c001`
     - **Type:** Linux
     - **Version:** Red Hat (64-bit)
     - **Network Adapter:** Host-only network matching the management node (e.g., `vagrantnet-vbox7`).

2. **PXE Boot Configuration in System Tab:**
   - Set the boot order to prioritize network boot.
   - Uncheck Enable EFI in the Extended Features.

3. **Network Configuration:**
   - Select Network Tab and following settings:
      - **Adapter 2 Tab:** Enable Network Adapter
      - **Attached to:** Host-only Network
      - **Name:** Check network of your Management VM and choose same Network
   - Advanced Options:
      - **Adapter Type:** Intel PRO/1000 MT Server (82545EM)
      - **Promiscuous Mode:** Allow All
      - **MAC Address:** Take a note of your MAC, we will use it after in the invetory

---

## 5. Configuration

### Inventory Configuration

Create and structure the inventory as follows:
```bash
inventory
├── cluster
│   ├── groups
│   │   ├── fn
│   │   ├── hw
│   │   └── os
│   └── nodes
│       ├── compute.yml
│       └── management.yml
└── group_vars
    ├── all
    │   ├── bb_core.yml
    │   ├── cluster_global.yml
    │   ├── networks.yml
    │   ├── pxe_stack.yml
    │   └── repositories.yml
    ├── hw_virtualbox
    │   └── fw.yml
    └── os_rhel9
        └── os.yml

mkdir -pv inventory/group_vars/all/hw_virtualbox
mkdir -pv inventory/group_vars/all/os_rhel9
mkdir -pv inventory/cluster/nodes
mkdir -pv inventory/cluster/groups
```

Example files:
`inventory/cluster/nodes/management.yml`:  

```yaml
all:
  hosts:
    management2:
      network_interfaces:
        - interface: eth1
          ip4: 10.76.0.10
          mac: 08:00:27:79:94:00
          network: net-admin
```

`inventory/cluster/nodes/compute.yml`:

```yaml
all:
  hosts:
    c001:
      network_interfaces:
        - interface: enp0s8                # Update to match VirtualBox's secondary network adapter
          ip4: 10.76.0.20                  # IP address for compute1 in your 10.75.0.0/24 network
          mac: 08:00:27:8f:c1:1e           # Replace with the actual MAC address of c001's enp0s8 interface
          network: net-admin               # The network as defined in your `networks.yml`

```

`inventory/cluster/groups/fn`:

```yaml
[fn_management]
management2

[fn_compute]
c[001:001]
```

`inventory/cluster/groups/hw`:

```yaml
[hw_virtualbox]
management2
c001
```

`inventory/cluster/groups/os`:

```yaml
[os_rhel_9]
management2
c001
```

`inventory/group_vars/all/cluster_global.yml`:

```yaml
bb_domain_name: bluebanquise-cluster.local
bb_time_zone: Europe/Paris
bb_cluster_name: bluebanquise-cluster
```

`inventory/group_vars/all/networks.yml`:

```yaml
networks:
  net-admin:
    subnet: 10.76.0.0        # Cluster's private subnet
    prefix: 24               # Subnet size (/24 for 255.255.255.0)
    services_ip: 10.76.0.10   # Services IP for BlueBanquise
    external_dns:
      - 8.8.8.8              # Primary external DNS (e.g., Google DNS)
      - 8.8.4.4              # Secondary external DNS
```

`inventory/group_vars/all/pxe_stack.yml`:

```yaml
pxe_stack_hw_equipment_type: server  # Servers are always added to PXE
pxe_stack_os_operating_system:
  distribution: redhat
  distribution_version: 9.5        # Minor version is not mandatory but usefull for Ubuntu (22 == 22.04 or 22.10?)
  distribution_major_version: 9

pxe_stack_hw_console: ttyS1,115200               # If using a remote server with a serial console, set it here
pxe_stack_os_kernel_parameters:      # If specific parameters are needed. I recommend to add least 'nomodeset' if server have an attached GPU
pxe_stack_hw_kernel_parameters:      # If you need to specify it as hw level instead of os level (for inventory readbility)

pxe_stack_os_keyboard_layout: us     # us, fr, etc.
pxe_stack_os_system_language: en_US.UTF-8  # You should not update this if you want to google issues...
pxe_stack_time_zone: Europe/Paris       # Ensure time zone set here is coherent for your whole cluster

pxe_stack_enable_root: false               # Disable root by default, and create a sudo user instead
pxe_stack_sudo_user: bluebanquise          # Name of the sudo user
pxe_stack_sudo_user_home: /var/lib/bluebanquise    # $HOME of the sudo user. Avoid /home/XXXX to prevent later issues.
pxe_stack_sudo_is_passwordless: true       # Set sudo user as passwordless sudoer

pxe_stack_os_admin_ssh_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGnai9ixfM22/8Sodbg7aYGggkrv/60cnK44UBkRfJxP bluebanquise@management2   # Add here your server(s) !! PUBLIC !! ssh key(s)

pxe_stack_os_access_control: disabled     # If SELinux or AppArmor (RHEL / Ubuntu only) should be let activated
pxe_stack_os_firewall: false               # If firewall (RHEL only for now) should be let activated

# WARNING! If nothing is set for partitioning,
# automatic partitioning will be activated.
pxe_stack_os_partitioning:                 # Set partitioning. Use raw OS format: kickstart for RHEL, preseed for Debian, etc.
                                           # Leave empty for automated partitioning

pxe_stack_os_pxe_images_root: http://${next-server}/pxe/netboots/redhat/9/x86_64/             # Specify a custom images root for PXE other than default http://${next-server}/pxe/netboots/${eq-distribution}/${eq-distribution-version}/${eq-architecture}/
pxe_stack_os_pxe_repository_root:          # Specify a custom os base repository root for PXE other than default http://${next-server}/repositories/${eq-repositories-environment}/${eq-distribution}/${eq-distribution-version}/${eq-architecture}/

```

`inventory/group_vars/all/repositories.yml`:

```yaml
bb_repositories:
  - name: bluebanquise
    baseurl: http://bluebanquise.com/repository/releases/latest/el9/x86_64/bluebanquise/
    enabled: 1
    state: present
```

`inventory/group_vars/hw_virtualbox/fw.yml`:

```yaml
hw_equipment_type: server 
```

`inventory/group_vars/os_rhel9/os.yml`:

```yaml
os_operating_system:
  distribution: redhat
  distribution_major_version: 9

#os_kernel_parameters:
os_keyboard_layout: us
os_system_language: en_US.UTF-8

#os_admin_ssh_keys:
- ssh-ed25519 <Pub-key of bluebanquise User> bluebanquise@management2 # Public ssh keys to deploy

os_access_control: disabled
os_firewall: false

os_partitioning: |
  clearpart --all --initlabel
  autopart --type=plain --fstype=ext4

os_admin_password_sha512: $6$JLtp9.SYoijB3T0Q$q43Hv.ziHgC9mC68BUtSMEivJoTqUgvGUKMBQXcZ0r5eWdQukv21wHOgfexNij7dO5Mq19ZhTR.JNTtV89UcH0

```

### Management Node setup

At this point, BlueBanquise configuration is done. We are ready to deploy the cluster.

We are going to proceed in the following order:

1. Deploy configuration on management2 node
2. Deploy fresh OS on the other nodes, from management2
3. Deploy configuration on the other nodes (Manual configuration in VirtualBox).

It is assumed that you already have deployed a fresh operating system on the management node management2.

#### Install Vital Dependencies

Use the provided bootstrap tool to install needed dependencies for your current system (recent python) and setup bluebanquise user. Note that you need the `sudo` command to be installed on the system.

Using root user (or a sudo user), launch the bootstrap script.

The script will install needed packages (mostly python), create the `bluebanquise` user with home at `/var/lib/bluebanquise`, set this user sudoer, install Ansible in a virtual environment in this user’s home, and generate an ssh keys pair for this user.

Script is verbose to help you debug in case of issues.

```bash
curl -o online_bootstrap.sh https://raw.githubusercontent.com/bluebanquise/bluebanquise/master/bootstrap/online_bootstrap.sh
chmod +x online_bootstrap.sh
./online_bootstrap.sh
```

Now, login as bluebanquise user. Remaining documentation assumes you are using the bluebanquise user.

```bash
sudo su - bluebanquise
```

#### Management deployment

  1. Import Inventory

     Import the inventory previsouly created in this documentation into `/var/lib/bluebanquise/inventory`

  2. Import management playbook

Create a playbook folder at `/var/lib/bluebanquise/`

```bash
mkdir -pv $HOME/playbooks

```
Copy from your host `playbooks/managements.yml` to `/var/lib/bluebanquise/playbooks` with the following content:

```yaml
---
- name: management playbook
  hosts: "fn_management"
  roles:

    # Infrastructure

    - role: bluebanquise.infrastructure.hosts_file
      tags: hosts_file
    - role: bluebanquise.infrastructure.set_hostname
      tags: set_hostname
    - role: bluebanquise.infrastructure.repositories
      tags: repositories
    - role: bluebanquise.infrastructure.nic
      tags: nic
    - role: bluebanquise.infrastructure.dhcp_server
      tags: dhcp_server
    - role: bluebanquise.infrastructure.dns_client
      tags: dns_client
    - role: bluebanquise.infrastructure.dns_server
      tags: dns_server
    - role: bluebanquise.infrastructure.http_server
      tags: http_server
    - role: bluebanquise.infrastructure.pxe_stack
      tags: pxe_stack
    - role: bluebanquise.infrastructure.ssh_client
      tags: ssh_client
    - role: bluebanquise.infrastructure.time
      tags: time
      vars:
        time_profile: server
```
#### Others required dependencies:

1. Core variables and Jinja2 extensions

In order to use BlueBanquise collections, you need the core variables, that contain the logic (BlueBanquise relies on a centralized logic to easily impact all roles at once).

To install core variables, you can either:

- Copy file bb_core.yml into your inventory at `group_vars/all/` level

2. Install collections

To install BlueBanquise collections, you can use the ansible-galaxy command:

```bash
ansible-galaxy collection install git+https://github.com/bluebanquise/bluebanquise.git#/collections/commons,master -vvv --upgrade
ansible-galaxy collection install git+https://github.com/bluebanquise/bluebanquise.git#/collections/infrastructure,master -vvv --upgrade
```

### PXE Stack

#### Description

This role provides the whole PXE stack needed to deploy computers over the network (assuming coupled with a dhcp server). This role is one of the major role of the BlueBanquise project.

#### Diskfull OS images location

In order to deploy diskfull servers, the role need administrator to provide OS images manually. Procedure depends of each OS.

All these steps have to be done on the PXE server. You can mix OS distributions and architectures (deploy an Ubuntu 22.04 arm64 from an x86_64 RHEL 9 server). Just be carefull of path, as on Suse servers, path is /srv/www/htdocs and not /var/www/html, adapt to your needs or deploy the role first so it creates pxe folders for you.

Path targeted by the role configuration files is the following: http://{next-server}/pxe/netboots/<distribution_name>/<distribution_version or distribution_major_version>/<CPU arch>/

**RHEL like**
Download DVD standalone iso (or equivalent). Example for RockyLinux 9: `https://download.rockylinux.org/pub/rocky/9/isos/x86_64/Rocky-9.5-x86_64-dvd.iso`

Create then dedicated folder and mount or copy iso content inside this folder:

```bash
sudo mkdir -pv /var/www/html/pxe/netboots/redhat/9/x86_64/iso
sudo mount /vagrant/Rocky-9.5-x86_64-dvd.iso /var/www/html/pxe/netboots/redhat/9/x86_64/iso
```

### Apply management2 configuration

Lets apply now the whole configuration on management2. It can take some time depending on your CPU and your hard drive, and your network connection when using external repositories.

We first ensure our NICs are up, so the repositories part is working. Ensure not to cut your connection if working remotely.

```bash
ansible-playbook playbooks/managements.yml -b -i inventory --limit management2 --tags set_hostname,nic
```

Check interfaces are up (check using ip a command), and then setp repositories:

```bash
ansible-playbook playbooks/managements.yml -b -i inventory --limit management2 --tags repositories
```

Then play the whole playbook:

```bash
ansible-playbook playbooks/managements.yml -b -i inventory --limit management2 --skip-tags dns_client
```

Execute just with tag pxe_stack:

```bash
ansible-playbook playbooks/managements.yml -b -i inventory --limit management2 --tags pxe_stack
```


And wait…

If all went well, you can check that all services are up and running.

### bluebanquise-bootset usage

Once the role is deployed, and hosts gathered into /etc/bluebanquise/bootset/nodes_parameters.yml, the bluebanquise-bootset tool can be used to manipulate remote hosts PXE boot. By default, 3 states can be defined for each host:

- **osdeploy:** the remote host will deploy/redeploy its operating system, using inventory equipment parameters of its equipment profile group.
- **disk:** the remote host will boot on disk. This parameter is automatically set after a successful osdeploy.
- **diskless:** the remote host will boot using a diskless mechanism. This diskless boot is generic, and is handled by an optional external role.

Again, consider that if you set an host to osdeploy, and that it succeed its deployment, stack will automatically set the host into disk boot for next boot, to avoid infinite reinstallation loop (this is done using a CGI script set along apache http server).

To get bluebanquise-bootset help, use:

```bash
bluebanquise-bootset -h
```

To ask an host to deploy/redeploy its operating system, use:

```bash
bluebanquise-bootset -n c001 -b osdeploy
```

If some inventory parameters related to the host have been updated recently, it may be required to force files regeneration instead of simply modifying them. To do so, use:

```bash
bootset-bootset -n c001 -b osdeploy -f update
```

## 6. Deploy C001 Node

Using your IDE of VirtualBox Start the c001, will be boot in the Network Card (PXE Boot), if not review respective configuration. 

If everything was configured right, your node c001 will be deployed with Rocky Linux 9.5

You can verify the progress through log files in your management node, using commands, such as:

**On RHEL/Suse like systems:**

```bash
sudo tail -f /var/log/httpd/*
```

## 7. References:

- [Configure BlueBanquise from Offical Documentation](https://bluebanquise.com/documentation/configure_bluebanquise.html)
- [Deploy Cluster](https://bluebanquise.com/documentation/deploy_cluster.html)
- [README from Github BlueBanquise project](https://github.com/bluebanquise/bluebanquise)
- [PXE Stack - README from Github BlueBanquise project](https://github.com/bluebanquise/bluebanquise/blob/master/collections/infrastructure/roles/pxe_stack/README.md)
- [Error in Vagrant on Rocky Linux 9.4](https://medium.com/@kjavaman12/how-to-fix-no-usable-default-provider-could-be-found-for-your-system-error-in-vagrant-on-rocky-67498b578670)
